packages/react-magma-dom/src/components/StyledButton/index.tsx

leaving the type as default causes buttons inside forms without a type to submit the form; this is
noticable when there's something like a dropdown
fix #192

fix(button): default type to ButtonType.button

---

packages/react-magma-dom/src/components/DatePicker/CalendarHeader.tsx

fix(date-picker): fix capitalizing a string that doesn't exist

---

.changeset/red-falcons-cry.md
packages/react-magma-dom/src/components/IconButton/IconButton.stories.tsx
packages/react-magma-dom/src/components/StyledButton/index.tsx

Creating components inside render function will force React to re-mount all children without attempts at reconciliation, which is an absolute antipattern. This is an issue when you want to do some transitions or animations, as demonstrated on a newly added story for IconButton. Without the fix, `SpinnerWrapper` and `ChildrenWrapper` are new functions on every render, React is forced to assume these are different components and throws out their render trees, which aborts any ongoing events.
IconButton story is just an example to demonstrate the problem.

fix StyledButton: move creation of wrappers outside of StyledButton render function

---

.changeset/early-melons-dress.md
packages/react-magma-dom/src/components/Tabs/Tabs.test.js
packages/react-magma-dom/src/components/Tabs/Tabs.tsx

Currently, `onChange` is not called when switching Tabs using keyboard and not clicking them. This can introduce bugs due to inconsistency.

fix(Tabs): call onChange function when tab panel is changed by keyboard navigation

---

.changeset/tall-toes-walk.md
packages/react-magma-dom/src/components/Tag/Tag.tsx

Fix https://github.com/cengage/react-magma/issues/566 
Updating the cursor for tags that are disabled and have an icon/delete

fix(tag.tsx): Disabled tags have the correct cursor

---

.changeset/tame-jobs-march.md
packages/react-magma-dom/src/components/Tag/Tag.stories.tsx

Fix https://github.com/cengage/react-magma/issues/565
Preview for Disabled and Disabled Inverse Tags now updates as the controls are changed.

fix(tag.stories.tsx): Preview updates when control props are toggled

---

.changeset/hungry-items-buy.md
packages/react-magma-dom/src/components/Select/Select.stories.tsx

fix #390 & #562
_After https://github.com/cengage/react-magma/pull/626 was merged, I noticed I missed something. It works now_

fix(select.stories.tsx): fix Select multi example

---

.changeset/rebrand-colors.md
packages/dropzone/src/components/dropzone/Dropzone.test.js
packages/react-magma-dom/src/components/Alert/__snapshots__/Alert.test.js.snap
packages/react-magma-dom/src/components/Button/__snapshots__/Button.test.js.snap
packages/react-magma-dom/src/components/Heading/__snapshots__/Heading.test.js.snap
packages/react-magma-dom/src/components/IconButton/__snapshots__/IconButton.test.js.snap
packages/react-magma-dom/src/components/SkipLink/SkipLink.test.js
packages/react-magma-dom/src/components/SkipLink/__snapshots__/SkipLink.test.js.snap
packages/react-magma-dom/src/components/StyledButton/StyledButton.test.js
packages/react-magma-dom/src/components/Toast/Toast.test.js
packages/react-magma-dom/src/components/Tooltip/__snapshots__/Tooltip.test.js.snap
packages/react-magma-dom/src/theme/magma.ts
packages/react-magma-dom/src/theme/magmaColors.ts

Adding the new rebrand colors per #648.
For now, I am leaving the legacy colors in the file until we transition all components to the new colors to avoid breaking anything. 
Colors can be accessed like: `theme.colors.primary` (which defaults to 500) or `theme.colors.primary600`

feat(magmacolors.ts): Adding new rebrand colors

---

.changeset/rebrand-processBar.md
packages/react-magma-dom/src/components/ProgressBar/ProgressBar.stories.tsx
packages/react-magma-dom/src/components/ProgressBar/ProgressBar.test.js
packages/react-magma-dom/src/components/ProgressBar/index.tsx
website/react-magma-docs/src/pages/api/progress-bar.mdx

BREAKING CHANGE: Progress Bar `pop` and `pop02` colors have been removed.
re #478 & #479

feat(progressbar): updating processBar colors

---

.changeset/homepage-focus-docs.md
website/react-magma-docs/src/components/Masthead/index.js

GitHub icon in the header of the homepage had 2 focus states:

docs(homepage): update focus on GitHub header icon

---

.changeset/tooltip-position.md
packages/react-magma-dom/src/components/NativeSelect/NativeSelect.stories.tsx
packages/react-magma-dom/src/components/StyledButton/index.tsx
packages/react-magma-dom/src/components/Tooltip/Tooltip.stories.tsx
packages/react-magma-dom/src/components/Tooltip/index.tsx
website/react-magma-docs/src/pages/api/tooltip.mdx

fix #752
Also, I noticed a console warning that the following icons are deprecated, so I figured we should update our docs to use the non-deprecated versions.
```
CircleRightIcon,
CircleLeftIcon,
CircleDownIcon,
CircleUpIcon
```

fix(tooltip): fix tooltip position bug

---

.changeset/dropdown-disabled.md
packages/react-magma-dom/src/components/Dropdown/Dropdown.stories.tsx
packages/react-magma-dom/src/components/Dropdown/DropdownMenuItem.tsx

Updated Storybook to directly address #544 + #545, and I noticed that inverse && disabled items were the wrong color

fix(dropdown): update dropdown item `isInverse` && `disabled` color

---

.changeset/table-pagination-inverse.md
packages/react-magma-dom/src/components/Table/Table.stories.tsx
packages/react-magma-dom/src/components/Table/TablePagination.tsx

fix(table): add `isInverse` support for TablePagination dropdowns

---

.changeset/native-select-windows.md
packages/react-magma-dom/src/components/Banner/Banner.stories.tsx
packages/react-magma-dom/src/components/NativeSelect/NativeSelect.tsx

fix #831 
**Tested with BrowserStack:**
Windows > Chrome:
Windows > Firefox:
Windows > Opera:

fix(nativeselect): add background color to the options for `isInverse`

---

.changeset/datagrid_sortable.md
.changeset/pre.json
packages/react-magma-dom/src/components/Datagrid/Datagrid.stories.tsx
packages/react-magma-dom/src/components/Datagrid/Datagrid.test.js
packages/react-magma-dom/src/components/Datagrid/Datagrid.tsx
packages/react-magma-dom/src/components/Table/Table.stories.tsx
packages/react-magma-dom/src/components/Table/Table.tsx
packages/react-magma-dom/src/components/Table/TableRow.test.js
packages/react-magma-dom/src/components/Table/TableRow.tsx
website/react-magma-docs/src/pages/api/datagrid.mdx

feat(datagrid): Add `isSortableBySelected` prop to DataGrid, allowing tables to be sorted by the selected items.

---

.changeset/pagination-a11y.md
packages/react-magma-dom/src/components/Pagination/Pagination.tsx

fix #508 #509 #510 #511 #512 #513
---
**Before:**
**After:**

fix(pagination): fix Pagination a11y issue regarding `<ul>` only having `<li>` as children

---

.changeset/datagrid-a11y.md
packages/react-magma-dom/src/components/Datagrid/Datagrid.stories.tsx
packages/react-magma-dom/src/components/Table/TableRow.tsx
website/react-magma-docs/src/pages/api/datagrid.mdx

fix #873
In addition, add better accessibility to sort by selectable examples in storybook and docs.

fix(datagrid): add aria-label to sort by selectable button

---

.changeset/anchor-color-landing.md
.changeset/anchor-color.md
packages/react-magma-dom/src/components/Hyperlink/Hyperlink.stories.tsx
packages/react-magma-dom/src/theme/GlobalStyles/index.tsx
website/react-magma-landing/static/styles.css

Issue: #900
Fix our Global style for anchors in react-magma-dom and our landing page.
- Look at storybook under the Hyperlink story
- Confirm in the docs site that links on the pages have the correct styling

fix(globalstyles): fix default `a:hover` color to match Hyperlink

---

.changeset/fix-helpicon.md
packages/react-magma-dom/src/components/Input/Input.stories.tsx
packages/react-magma-dom/src/components/InputBase/index.tsx
packages/react-magma-dom/src/components/PasswordInput/index.tsx

Issue #909
Fix placement of `children` passed to Input component. Made it compatible with `isClearable` (which it wasn't previously)
**before**
**after**
- Test all Inputs (Input, PasswordInput, DatePicker) and ensure they are behaving as expected
- Specifically, test Input > With Children and confirm that the component visually looks how we expect. Test `medium`, `large`, `isClearable`.

fix(input): fix placement of `children` inside Input component 

---

.changeset/appbar-spacing.md
packages/react-magma-dom/src/components/AppBar/AppBar.stories.tsx
website/react-magma-docs/src/pages/api/appbar.mdx

Issue: #881
Fix the storybook and react-magma-docs example for AppBar Tabs so that components no longer overlap
**before**
**after**

docs(appbar): fix components overlapping in AppBar Tabs example

---

.changeset/icons-charts.md
.changeset/icons-docs.md
.changeset/icons-dom.md
.changeset/icons-dropzone.md
.changeset/icons-header.md
.changeset/icons-schema.md
package-lock.json
packages/charts/package.json
packages/dropzone/package.json
packages/react-magma-dom/package-lock.json
packages/react-magma-dom/package.json
packages/schema-renderer/package.json
patterns/header/package.json
website/react-magma-docs/package.json

Issue: #928 
Updating the react-magma-icons version to 2.3.4 in all packages. This will allow our users to have access to the newest icons (https://github.com/cengage/react-magma-icons/pull/2)
- [N/A] New and existing unit tests pass locally with my changes
Review that the [docs site](https://docs-preview-932--upbeat-sinoussi-f675aa.netlify.app/api/icon/) includes the 4 new icons:
BookProjectWfIcon,
BooksWfIcon,
ProjectWfIcon,
TasksWfIcon,

build(react-magma-icons): bump react-magma-icons to 2.3.4

---

.changeset/table-stories.md
packages/react-magma-dom/src/components/Table/Table.stories.tsx

Storybook example for tables where the number of rows is adjustable. For @hkrishna29 and testing purposes.

docs(table): Storybook example with adjustable number of rows

---

.changeset/table-a11y-focus.md
packages/react-magma-dom/src/components/Table/Table.tsx

Issue: #874, #875, #878
Added a `tabIndex` to the Table container. This makes Tables focusable, but also added styles so that the table is only focusable with keyboard navigation and not when clicked on with a mouse. This removes the a11y violation for Table and DataGrid.
Indirectly, this also addresses #271.
**before**
**after**
Test the following components in different browses, in mobile and desktop screens. Confirm there are no accessibility issues
- DataGrid: https://storybook-preview-938--upbeat-sinoussi-f675aa.netlify.app/?path=/story/datagrid--default
- Table: https://storybook-preview-938--upbeat-sinoussi-f675aa.netlify.app/?path=/story/tabl …

fix(table): add keyboard only focus to tables without a focusable element

---

.changeset/combobox-inside-form.md
packages/react-magma-dom/src/components/Combobox/Combobox.stories.tsx
packages/react-magma-dom/src/components/Combobox/MultiCombobox.test.js
packages/react-magma-dom/src/components/Combobox/MultiCombobox.tsx

Issue: #953 
Added `type="button"` to the items inside a combobox. This should prevent the whole form submitting when an item gets removed.
_No visual change, just a change in the DOM_
- Confirm that after selecting more than one item, clicking one item to delete it does not submit the form

fix(combobox): items have a default `type="button"` to prevent issues inside form

---

.changeset/small-jokes-hide.md
website/react-magma-docs/src/pages/api-intro/changelog.mdx

fix #463
Issue: #463
-removed the markup for a link to allow for the sidebar link to navigate to the correct section in the changelog
- From Sidebar > Components > Changelog 
- Click 2.3.0 (2020-12-08)
- Verify the page navigates to the correct section.

docs(changelog): broken link to the 2.3.0 release

---

.changeset/tabs-disabled.md
packages/react-magma-dom/src/components/Tabs/Tab.test.js
packages/react-magma-dom/src/components/Tabs/Tab.tsx

Issue: #836
Updated the cursor for disabled tabs to be `not-allowed`

fix(tabs): disabled tabs have the disabled cursor

---

.changeset/search-placeholder.md
packages/react-magma-dom/src/components/Search/index.tsx

Issue: #955
Addressing one more use case for #955 where the Search component placeholder spacing needed adjustments when the user clicked on `isClearable` button.
- On the Search component with `isClearable` prop set to true, enter a long placeholder
- Type into the input
- Click the isClearable X
- Notice the spacing is correct

fix(search): components with long placeholders && `isClearable` have appropriate padding

---

.changeset/magma-icons-charts.md
.changeset/magma-icons-docs.md
.changeset/magma-icons-dom.md
.changeset/magma-icons-dropzone.md
.changeset/magma-icons-header.md
.changeset/magma-icons-schema.md
packages/charts/package.json
packages/dropzone/package.json
packages/react-magma-dom/package-lock.json
packages/react-magma-dom/package.json
packages/schema-renderer/package.json
patterns/header/package.json
website/react-magma-docs/package.json

Issue: #969
Update packages to version 2.3.6 of react-magma-icons (includes fixed DirectionsRailwayIcon and updated BooksWfIcon)
Confirm icons are updated

chore: Update react-magma-icons to v2.3.6

---

.changeset/feat-alertChildren.md
packages/react-magma-dom/src/components/Alert/Alert.stories.tsx
packages/react-magma-dom/src/components/Alert/Alert.test.js
packages/react-magma-dom/src/components/Alert/__snapshots__/Alert.test.js.snap
packages/react-magma-dom/src/components/Alert/index.tsx
packages/react-magma-dom/src/components/AlertBase/index.tsx
packages/react-magma-dom/src/components/Banner/Banner.stories.tsx
packages/react-magma-dom/src/components/Banner/Banner.test.js
packages/react-magma-dom/src/components/Banner/index.tsx
website/react-magma-docs/src/pages/api/alert.mdx
website/react-magma-docs/src/pages/api/banner.mdx

Issue: # [992](https://github.com/cengage/react-magma/issues/992)
Added `additionalContent` prop to Alerts and Banners for right aligned children elements such as buttons and badges.

feat - Support adding children on the right side of Alerts

---

.changeset/toggle-button-hover.md
packages/react-magma-dom/src/components/ToggleButton/ToggleButton.tsx

Issue: #904
Fix hover state for ToggleButton to follow requirement:
```
-- 5.2 Regardless of whether the button is currently on or off, it gets the hover and pressed styling when triggered
```
Hover over a ToggleButton that is checked, and then hover over a button that is not.

fix(togglebutton): fix hover states

---

.changeset/icons.md
package-lock.json
packages/charts/package.json
packages/dropzone/package.json
packages/react-magma-dom/package-lock.json
packages/react-magma-dom/package.json
packages/schema-renderer/package.json
patterns/header/package.json
website/react-magma-docs/package-lock.json
website/react-magma-docs/package.json

Issue: none
Update react-magma-icons to v3.0.0. v2.4.1 has been deprecated because depending on React17 should be a breaking change, not a minor change.

chore(icons): Update react-magma-icons to v3.0.0

---

.changeset/tooltip-docs.md
website/react-magma-docs/src/pages/api/tooltip.mdx

Issue: none
The docs referenced a `trigger` prop that has not existed in 3 years. So, I removed that :) 
Ensure there are no references to `trigger` prop in the tooltip docs.

docs(tooltip): Update docs

---

.changeset/docs-select.md
.changeset/multiselect-align.md
packages/react-magma-dom/src/components/Select/ItemsList.tsx
packages/react-magma-dom/src/components/Select/MultiSelect.tsx
website/react-magma-docs/src/components/PageContent/index.js
website/react-magma-docs/src/pages/api/dropdown.mdx
website/react-magma-docs/src/pages/api/input.mdx
website/react-magma-docs/src/pages/api/select.mdx

_Issue: none_
- Updated Select docs to be in a more coherent order (basic props at the top, all customizations together, etc.)
- Updated Multi Select placeholder spacing
- Updated Input doc examples to use the InputType enum (instead of a string)
**before**
**after**
- Navigate to the Select docs site and make sure the content flows better
- Confirm that the spacing is updated for multi selects

docs(select): Reorganize docs

---

.changeset/docs-toggle.md
website/react-magma-docs/src/pages/api/toggle-button-group.mdx
website/react-magma-docs/src/pages/api/toggle-button.mdx

Issue: none
While working on something completely different I noticed the ToggleButton and ToggleButtonGroup docs were using the old structure, causing the layout to break.
_before_
Navigate to each of those docs and confirm they match the layout of other doc pages.

docs(toggleButton): Update ToggleButton and ToggleButtonGroup docs

---

.changeset/charcounter-ref.md
packages/react-magma-dom/src/components/CharacterCounter/CharacterCounter.tsx

Add ref to character counter, and get rid of this warning. 
We had previously done this in v4, but missed the fix in v3.

fix(CharacterCounter): Add  to Character Counter.

---

.changeset/dropdown-noitems.md
packages/react-magma-dom/src/components/ButtonGroup/__snapshots__/ButtonGroup.test.js.snap
packages/react-magma-dom/src/components/Dropdown/Dropdown.stories.tsx
packages/react-magma-dom/src/components/Dropdown/Dropdown.test.js
packages/react-magma-dom/src/components/Dropdown/Dropdown.tsx
packages/react-magma-dom/src/components/Dropdown/DropdownContent.tsx
packages/react-magma-dom/src/index.ts
website/react-magma-docs/src/pages/api/dropdown.mdx

Issue: #1013
This should fix two issues:
- Dropdowns without items should get focus on the entire content
- In Safari, Dropdowns without items should be closable when the Escape button is clicked
Update documentation to separate Dropdowns with filters, forms and informational content.
- Confirm that focus goes to the dropdown menu
- Confirm with a screenreader that content inside the dropdown without items is read
- Confirm that the dropdown without items can be properly navigated with a keyboard
- Confirm that in Safari, clicking escape after opening a dropdown without items closes the menu
- Test these changes in all the browsers

fix(dropdown): Dropdowns without `DropdownMenuItem` will get focused on open

---

.changeset/charcounter-initialvalue.md
packages/react-magma-dom/src/components/CharacterCounter/CharacterCounter.stories.tsx
packages/react-magma-dom/src/components/CharacterCounter/CharacterCounter.test.js
packages/react-magma-dom/src/components/Input/Input.test.js
packages/react-magma-dom/src/components/Input/index.tsx
packages/react-magma-dom/src/components/Textarea/Textarea.stories.tsx
packages/react-magma-dom/src/components/Textarea/Textarea.test.js
packages/react-magma-dom/src/components/Textarea/index.tsx

_Issue: none_
Update Input and Textarea to update the character length when the default value changes. This way, when the component with a character counter gets re-rendered with a different default value, the count will be up to date.
- [n/a] I have made corresponding changes to the documentation
Test the following for both the Input and Textarea:
- Confirm that on Storybook, if the default value is changed, the character counter is updating consistently
- Try to recreate the reported use case (https://screenpal.com/watch/c0fqouVzjFj) on CodeSandbox and confirm this would no longer be an issue:
Test changing `hi` to `hiiiiii`
```
export function Example() {
return (
<Input
maxLength={4}
value={"hi"}
labelText="Initial Value Character Counter"
/>
);
}
```

fix(CharCounter): Update calculation for character length on rerender

---

.changeset/disabled-multiCombo.md
packages/react-magma-dom/src/components/Combobox/Combobox.stories.tsx
packages/react-magma-dom/src/components/Combobox/MultiCombobox.test.js
packages/react-magma-dom/src/components/Combobox/MultiCombobox.tsx
packages/react-magma-dom/src/components/Select/shared.ts

Issue: #1057
Fixed the Multi Combobox so that all interactive items inside it cannot be clicked when disabled
- Confirm that multi comboboxes with selected items can't be deselected 
- Confirm the inverse state
- Confirm the styles of the disabled, selected items
- Confirm that when using isClearable, that button also cannot be clicked

fix(combobox): Disabled Multi Combobox disables the buttons inside it

---

.changeset/fix-characterCounterProp.md
packages/react-magma-dom/src/components/CharacterCounter/CharacterCounter.stories.tsx
packages/react-magma-dom/src/components/CharacterCounter/CharacterCounter.test.js
packages/react-magma-dom/src/components/CharacterCounter/CharacterCounter.tsx
packages/react-magma-dom/src/components/Combobox/Combobox.stories.tsx
packages/react-magma-dom/src/components/FormFieldContainer/FormFieldContainer.tsx
packages/react-magma-dom/src/components/Input/Input.test.js
packages/react-magma-dom/src/components/Input/InputMessage.tsx
packages/react-magma-dom/src/components/Input/index.tsx
packages/react-magma-dom/src/components/InputBase/index.tsx
packages/react-magma-dom/src/components/Textarea/Textarea.stories.tsx
packages/react-magma-dom/src/components/Textarea/Textarea.test.js
packages/react-magma-dom/src/components/Textarea/index.tsx
website/react-magma-docs/src/pages/api/character-counter.mdx
website/react-magma-docs/src/pages/api/input.mdx
website/react-magma-docs/src/pages/api/textarea.mdx

Issue: # [1037](https://github.com/cengage/react-magma/issues/1037)
- Added two new props of 'maxCount' replacing 'maxLength' for enabling the Character Counter and 'hasCharacterCounter'. If 'hasCharacterCounter' is set to false, it hides the Character Counter.
Test both the regular **Input** and **Textarea** components:
- Confirm the Character Counter appears when `maxCount` is set.
- Confirm `maxLength` still works as a Character Counter.
- Confirm `maxLength` works as a native maxlength when `hasCharacterCounter` is set to false.

fix(CharacterCounter): Replace `maxLength` prop with `maxCount` and add `hasCharacterCounter` prop

---

.changeset/fix-docsDatagrid.md
website/react-magma-docs/src/pages/api/datagrid.mdx

Issue: # [1058](https://github.com/cengage/react-magma/pull/1058)
- Bug fix (non-breaking change which fixes an issue)
- Amended missing example under the "Selectable and Sortable" example within the doc site.
Go to our doc site -> Selectable and Sortable -> Ensure example is visible and functions.

Fix - Documentation - DataGrid

---

.changeset/fix-characterCounterStyling.md
packages/react-magma-dom/src/components/CharacterCounter/CharacterCounter.stories.tsx
packages/react-magma-dom/src/components/CharacterCounter/CharacterCounter.tsx
packages/react-magma-dom/src/components/Input/index.tsx
packages/react-magma-dom/src/components/Textarea/Textarea.stories.tsx
packages/react-magma-dom/src/components/Textarea/index.tsx

Issue: # [1037](https://github.com/cengage/react-magma/issues/1037)
- Fixed bugs for Character Counter involving:
- Unintentional red error border when `hasCharacterCounter` is `false` and `maxCount` is `true`.
- Bold text on Character Counter before user input removed.
- `maxLength` native behavior overriding `maxCount` or `maxLength` if `hasCharacterCounter` is `true`.
- [ NA ] I have made corresponding changes to the documentation
- [ NA ] I have added tests that prove my fix is effective or that my feature works
- Verify that before you enter a value in Character Counter that the text weight is normal and _**not**_ bold.
- In `Input` set `hasCharacterCounter` to `false` and then set a numeric value for `maxCount` and verify that no red border appears after you exceed the set numbered …

Fix/character counter styles and maxLength conflict

---

.changeset/charCounter.md
packages/react-magma-dom/src/components/CharacterCounter/CharacterCounter.stories.tsx
packages/react-magma-dom/src/components/Input/index.tsx
packages/react-magma-dom/src/components/Textarea/index.tsx

Issue: #1037 
Address the bug where, when using both maxCount and maxLength, the error border appeared early
Use the maxCount and maxLength story to test all use cases

fix(characterCounter): Update maxLength/maxCount logic

---

.changeset/button-focus-stack.md
packages/react-magma-dom/src/components/Alert/__snapshots__/Alert.test.js.snap
packages/react-magma-dom/src/components/Button/__snapshots__/Button.test.js.snap
packages/react-magma-dom/src/components/ButtonGroup/__snapshots__/ButtonGroup.test.js.snap
packages/react-magma-dom/src/components/IconButton/__snapshots__/IconButton.test.js.snap
packages/react-magma-dom/src/components/SkipLink/__snapshots__/SkipLink.test.js.snap
packages/react-magma-dom/src/components/StyledButton/index.tsx

Issue: #1084 
Added `z-index` to focused buttons in order to ensure the focus outline stays fully visible
**before:**
**after:**
Play around with the following components and ensure the focus behaves as expected:
- ButtonGroup
- Pagination
- ToggleButton

fix(Button): Update button z-index when it's in focus to bring the focus outline to the front.

---

.changeset/input-focus-stack.md
packages/react-magma-dom/src/components/InputBase/index.tsx

Issue: none
Added z-index to focused inputs in order to ensure the focus outline stays fully visible
**before:**
**after:**
Play around with components that stack inputs next to buttons.

fix(Input): Update input z-index when it's in focus to bring the outline to front

---

.changeset/dropdown-noitems.md
.github/workflows/publish-next-patch.yml
packages/react-magma-dom/src/components/ButtonGroup/__snapshots__/ButtonGroup.test.js.snap
packages/react-magma-dom/src/components/Dropdown/Dropdown.stories.tsx
packages/react-magma-dom/src/components/Dropdown/Dropdown.test.js
packages/react-magma-dom/src/components/Dropdown/Dropdown.tsx
packages/react-magma-dom/src/components/Dropdown/DropdownContent.tsx
website/react-magma-docs/src/pages/api/dropdown.mdx

Issue: #1063 
We had fixed this dropdown issue in https://github.com/cengage/react-magma/commit/cca876b3a73cf54418da54501712c70b599c7f10 but that commit did not get copied to v3.
- Confirm that focus goes to the dropdown menu
- Confirm with a screenreader that content inside the dropdown without items is read
- Confirm that the dropdown without items can be properly navigated with a keyboard
- Confirm that in Safari, clicking escape after opening a dropdown without items closes the menu
- Test these changes in all the browsers

fix(dropdown): Dropdowns without DropdownMenuItem will get focused on open

---

.changeset/fix-inputBase.md
packages/react-magma-dom/src/components/Input/Input.test.js
packages/react-magma-dom/src/components/InputBase/InputBase.stories.tsx
packages/react-magma-dom/src/components/InputBase/index.tsx

Issue: #1027
-Fixed case where defaultValue is 0
-Navigate to storybook for InputBase, and observe that the input where defaultValue is set to `0` shows a `0`

fix(Input Base): Fixed case where default value of `0` did not render the default value in the input field

---

.changeset/fix-datePickerEscape.md
packages/react-magma-dom/src/components/DatePicker/DatePicker.test.js
packages/react-magma-dom/src/components/DatePicker/index.tsx

Issue: #264
Update DatePicker component to close only the panel when placed inside a modal despite a date being selected or not.
Test a DatePicker inside a modal:
- Without selecting a date, navigate to the calendar. Press ESC
- After selecting a date, navigate to the calendar. Press ESC
Both scenarios should only close the calendar panel
Confirm that the datepicker continues to work as expected when not used inside a modal

fix(DatePicker): Escape key only closes the panel

---

.changeset/inputHeight.md
packages/react-magma-dom/src/components/InputBase/index.tsx

Issue: none
Update Input height to match button sizes: 40px (instead of 42px) and 56px (instead of 58px)
Before:
After:
- Test all components that use inputs and ensure nothing is broken. 
- Test the 2 input sizes

fix(input): Update input height to 40px/56px

---

.changeset/nativeSelectHeight.md
packages/react-magma-dom/src/components/Input/Input.stories.tsx
packages/react-magma-dom/src/components/NativeSelect/NativeSelect.tsx

Issue: none
1. Updated NativeSelect so that the border is fully visible (had to make the component 38px + 2px of borders for a total of 40px
2. The Input story `with children` was confusing but nothing was broken:
- For example, we support icons for top, right and left (see  Icon Positions story). However, if the user wants to make the button interactive (like to use a tooltip like in the examples), we only support that for top and right. 
- If the user wants to use 2 icons, it can only be done with one to the left and one to the right.
- I created a new story for `with two icons` and made some modifications to the `with children` story to clear this up.
Before:
After:
Test Native Select and other …

fix(NativeSelect): Update NativeSelect height to match button sizes

---

.changeset/dropdownContent-falseChild.md
packages/react-magma-dom/src/components/Dropdown/Dropdown.test.js
packages/react-magma-dom/src/components/Dropdown/DropdownContent.tsx

Issue: #1131
Add support for `false` as a child of DropdownContent
Ensure that the following code works:
```
<Dropdown>
<DropdownButton>Basic Dropdown</DropdownButton>
<DropdownContent>
{false && <DropdownMenuItem>Menu item 1</DropdownMenuItem>}
<DropdownMenuItem>Menu item number two</DropdownMenuItem>
<DropdownMenuItem disabled>Disabled item</DropdownMenuItem>
</DropdownContent>
</Dropdown>
```

fix(DropdownContent): Handle `false` as child

---

.changeset/fix-labelsColors.md
packages/react-magma-dom/src/components/SelectionControls/StyledLabel.tsx
packages/react-magma-dom/src/components/Tabs/TabPanel.tsx

Issue: none
- Our docs site content, which is inside a TabPanel was using neutral500 instead of neutral700
- Labels for our form elements were using neutral500 instead of neutral700
This change affects:
- Checkbox
- IndeterminateCheckbox
- Label
- Radio
- Toggle
- Tabs

fix(StyledLabel/TabPanel): Update various labels and TabPanel content to be neutral700

---

.changeset/fix-radioGroup.md
packages/react-magma-dom/src/components/RadioGroup/index.tsx

Issue: #
Label inside RadioGroup is a span instead of a label.
Confirm a11y passes for RadioGroup

fix(RadioGroup): Radio Group label is now a span to improve a11y

---

.changeset/fix-passInputLarge.md
packages/react-magma-dom/src/components/InputBase/index.tsx
packages/react-magma-dom/src/components/PasswordInput/PasswordInput.stories.tsx
packages/react-magma-dom/src/components/PasswordInput/index.tsx

Issue: #1088
Fix placement of show / hide button in large password input. Also added input size to storybook and to the list of the component's props.
Before:
After:
- [n/a] I have added tests that prove my fix is effective or that my feature works
Test PasswordInput component in both the small and large size

fix(PasswordInput): Update placement of Show/Hide button on Large input size

---

.changeset/fix-expandableDropdown.md
.changeset/fix-expandableDropdownDisabled.md
packages/react-magma-dom/src/components/Dropdown/Dropdown.stories.tsx
packages/react-magma-dom/src/components/Dropdown/Dropdown.test.js
packages/react-magma-dom/src/components/Dropdown/DropdownExpandableMenuButton.tsx
packages/react-magma-dom/src/components/Dropdown/DropdownExpandableMenuListItem.tsx

Issue: # [1014](https://github.com/cengage/react-magma/issues/1014)
- Fixed disabled state on 'DropdownExpandableMenuListItem'.
- Fixed disabled hover background on 'DropdownExpandableMenuGroup'.
Confirm 'DropdownExpandableMenuListItem' supports a disabled state.
Verify 'DropdownExpandableMenuGroup' hover does **not** have a background.

Dropdown Expandable - QA review fixing disabled states

---

.changeset/fix-dropdownDocsStorybook.md
packages/react-magma-dom/src/components/Dropdown/Dropdown.stories.tsx
website/react-magma-docs/src/pages/api/dropdown.mdx

Issue: # [1014](https://github.com/cengage/react-magma/issues/1014)
- Removed Dropdown with Form example in docs under Dropdown
- Removed Form example in Storybook under Dropdown
-Confirm docs example of Dropdown with Form example is removed under Dropdown without Menu Items.
-Confirm Storybook example of Form is no longer under the Dropdown examples.

Fix - Dropdown - Removing docs and storybook examples of the Dropdown form

---

.changeset/chartColors.md
packages/react-magma-dom/src/theme/magma.ts

Issue: #
-Adding chartColors to theme.

adding chartColors to theme

---

.changeset/fix-additionalContentDocs.md
packages/react-magma-dom/src/components/FormFieldContainer/FormFieldContainer.tsx
website/react-magma-docs/src/pages/api/native-select.mdx
website/react-magma-docs/src/pages/api/select.mdx

Issue: #1114 
- Updated CodeSandbox examples to have correct imports, and to not have any errors (previously the examples were missing the fieldId prop)
Confirm that examples open in CodeSandbox

docs(Select/NativeSelect): Update AdditionalContent CodeSandbox examples

---

.changeset/feat-paragraphMargins.md
packages/react-magma-dom/src/components/Paragraph/Paragraph.stories.tsx
packages/react-magma-dom/src/components/Paragraph/Paragraph.test.js
packages/react-magma-dom/src/components/Paragraph/index.tsx
packages/react-magma-dom/src/components/Typography/index.tsx
website/react-magma-docs/src/pages/api/paragraph.mdx

- Added two new props `noBottomMargin` and `noTopMargin` for additional styling options.
- Got to Docs > Paragraph
- Ensure both additional examples of No Bottom Margin and No Top Margin appear appropriately

feat(Paragraph): New `noTopMargin` and `noBottomMargin` props that allow customization of which margin to remove.

---

.changeset/fix-modalStorybook.md
packages/react-magma-dom/src/components/Modal/Modal.stories.tsx

Issue: # [1173](https://github.com/cengage/react-magma/issues/1173)
- Fixing inverse example in Storybook
- Go to Storybook
- Open Modal > Inverse example
- Verify text is now white in the Modal body

Fix - Modal > Storybook > Inverse example

---

.changeset/nativeSelect-testId.md
packages/react-magma-dom/src/components/NativeSelect/NativeSelect.stories.tsx
packages/react-magma-dom/src/components/NativeSelect/NativeSelect.tsx

Issue: none
This issue was reported by the MAST team (https://jira.cengage.com/browse/HQL-11343) and was significant enough to warrant an immediate fix.
`StyledFormFieldContainer` should use the `testId` prop instead of `data-testid`.
Before:
When pulling this change locally, confirm there's no console warning and that the test id is in the DOM as expected

fix(NativeSelect): Fix issue with data-testid

---

.changeset/modal-isModalClosingControlledManually.md
packages/react-magma-dom/src/components/Modal/Modal.stories.tsx
packages/react-magma-dom/src/components/Modal/Modal.test.js
packages/react-magma-dom/src/components/Modal/Modal.tsx
website/react-magma-docs/src/pages/api/modal.mdx

Issue: # 1171
1. Run storybook;
2. Open the new example inside the Modal tab (CloseModalWithConfirmation);
3. With default implementation whenever the user clicks on the close icon (if it's a default close icon) RM will automatically close the modal. But in this example, you should see a confirmation modal on trying to close the main modal.

feat(modal): added new isModalClosingControlledManually property

---

.changeset/fix-NativeSelectPagination.md
packages/react-magma-dom/src/components/NativeSelect/NativeSelect.test.js
packages/react-magma-dom/src/components/NativeSelect/NativeSelect.tsx
packages/react-magma-dom/src/components/Table/TablePagination.test.js

Issue: # [1201](https://github.com/cengage/react-magma/issues/1201)
- Added a conditional layer to prevent additional wrapping of the `NativeSelect`. This fixes the selection issue documented in the bug ticket.
- Go to Storybook
- Go to Datagrid > default
- Within the table click on the Rows Per Page select and change from 10 to anything else
- Verify the new selection appears in the dropdown and the data in the table updates accordingly

fix(NativeSelect): Fixed related simple pagination issue with selected states not updating after selection.

---

.changeset/fix-BadgeHeight.md
packages/react-magma-dom/src/components/Badge/Badge.test.js
packages/react-magma-dom/src/components/Badge/index.tsx

Issue: # TBD
- Updates the `label` Badge height to properly align between the two variants, now both `label` and `counter` match.
- Open either Docs or Storybook
- Go to Badge
- Ensure the `label` version (default) shows a total pixel height of 24px.
- Ensure the `number` version shows a total pixel height of 24px.

Fix(Badge): Fixes the Badge height for the label version. Both label and counter variants are now 24px in height.

---

.changeset/time-picker-onchange.md
packages/react-magma-dom/src/components/TimePicker/TimePicker.stories.tsx
packages/react-magma-dom/src/components/TimePicker/TimePicker.test.js
packages/react-magma-dom/src/components/TimePicker/useTimePicker.ts

Issue: #1270 
Calling `updateTime('')` on `handleHourKeyDown` and `handleMinuteKeyDown`
Navigate to the TimePicker events story or docs site and confirm that pressing backspace clears the time value visually and on the event.

fix(TimePicker): Returns empty when backspace is pressed

---

.changeset/fix-datagrid.md
packages/react-magma-dom/src/components/Datagrid/Datagrid.test.js
packages/react-magma-dom/src/components/Datagrid/Datagrid.tsx

Issue: # [1201](https://github.com/cengage/react-magma/issues/1201)
- Fixed the select not updating when selected with a new value in Datagrid.
- Go to Datagrid
- Select a new value from the pagination select
- Confirm the newly selected value updates the visible rows
- Confirm select contains the proper value
- Open Docs
- Go to Datagrid
- Select a new value from the pagination select
- Confirm the newly selected value updates the visible rows
- Confirm select contains the proper value

Fix(Datagrid): Fixed the state of pagination select not updating the newly selected value.

---

.changeset/treeview-style.md
packages/react-magma-dom/src/components/TreeView/TreeItem.tsx
packages/react-magma-dom/src/components/TreeView/TreeView.stories.tsx
packages/react-magma-dom/src/components/TreeView/TreeView.test.js
website/react-magma-docs/src/pages/api/tree-view.mdx

Address the following bugs:
Retest the bugs above on Storybook

fix(TreeView): Update styles

---

.changeset/treeview-docs.md
packages/react-magma-dom/src/components/TreeView/useTreeItem.ts
website/react-magma-docs/src/pages/api/tree-view.mdx

Issue: #180 
- Update docs example where we were repeating an itemId (and itemIds need to be unique for proper behavior)
- In addition, hiding the `isDisabled` prop for now because it's not fully implemented. Added a ticket number to the TODOs.
Confirm that for the Basic Usage example in the docs site, the itemIds are all unique. Also confirm that when tabbing into the tree, if you press tab one more time, it navigates out of the tree.

docs(TreeView): Update example with duplicate IDs

---

.changeset/input-wrapperStyle.md
packages/react-magma-dom/src/components/Input/Input.stories.tsx
packages/react-magma-dom/src/components/Input/Input.test.js
packages/react-magma-dom/src/components/Input/InputMessage.tsx
packages/react-magma-dom/src/components/InputBase/index.tsx
packages/react-magma-dom/src/components/Label/index.tsx
website/react-magma-docs/src/pages/api/input.mdx

Issue: #
Add `inputWrapperStyle` prop to allow more flexibility with Input widths
Before:
After:

fix(Input): Add `inputWrapperStyle` prop

---

.changeset/hyperlink.md
.storybook/preview.tsx
packages/react-magma-dom/src/components/Hyperlink/Hyperlink.stories.tsx
packages/react-magma-dom/src/components/Hyperlink/Hyperlink.test.js
packages/react-magma-dom/src/components/Hyperlink/index.tsx
packages/react-magma-dom/src/index.ts
packages/react-magma-dom/src/theme/GlobalStyles/index.tsx
website/react-magma-docs/src/pages/api/hyperlink.mdx

Issue: #1120
- Added support for an icon on the left, right, or both sides of a Hyperlink
- Added `hasUnderline` prop that defaults to true
- Updated Hyperlink and native anchors hover color
Confirm all use cases for hyperlinks are working. Consider:
- styled as button or link
- inverse on/off
- hasUnderline on/off
- passing 1 icon
- passing 2 icons
- icon positions: left, right or both
- using it inside `<Paragraph>`, `<p>`, and other text wrappers

Hyperlink: Support Icons and toggling underline styling

---

.changeset/landing-version.md
website/react-magma-landing/scripts/build.js

Issue: -
During the last release, we removed support for React 15, which caused an extra card to appear in the landing page. This PR removes that

react-magma-landing: Remove extra card with version 15

---

.changeset/nativeSelect-arrow.md
packages/react-magma-dom/src/components/NativeSelect/NativeSelect.stories.tsx
packages/react-magma-dom/src/components/NativeSelect/NativeSelect.tsx
packages/react-magma-dom/src/components/Select/Select.stories.tsx

Issue: #1164 
- Updated arrow color for both inverse and not
- Updated spacing for arrow
- Added extra space so that, if the content is long, the arrow has a background to cover the long text
Before:
After:
Test the spacing and color of NativeSelects in both inverse and regular, with short and long content.

fix(NativeSelect): Update arrow placement and color

---

.changeset/timepicker-example.md
packages/react-magma-dom/src/components/TimePicker/TimePicker.stories.tsx

Issue: #1270 
Updated TimePicker Events Storybook example so that `onChange` only gets called once when the clear time button is clicked.
Confirm that onChange is only called once.

storybook(TimePicker): Update clear time example

---

.changeset/dropzone-files-browse.md
packages/dropzone/src/components/dropzone/Dropzone.test.js
packages/dropzone/src/components/dropzone/Dropzone.tsx

Issue: #1146 
Fix the 'Open File' menu to open on button click.
1.Go to dropzone in storybook
2.Try to open file by click `Browse Files`

fix(Dropzone): Open file browse on button click

---

.changeset/a11y-pagination.md
packages/react-magma-dom/src/components/Pagination/Pagination.test.js
packages/react-magma-dom/src/components/Pagination/Pagination.tsx

Issue: #1388 #1387 
- Updated `aria-current` from `true` to `page`
- Added `aria-label="pagination"`. This can be customized by adopters as well in case there are multiple paginations on the page.
- Verify the use of `aria-current`
- Verify that `aria-label` is visible on the nav property

fix(Pagination): Improved accessibility for classic pagination

---

.changeset/a11y-datagrid.md
packages/react-magma-dom/src/components/Datagrid/Datagrid.stories.tsx
packages/react-magma-dom/src/components/Datagrid/Datagrid.tsx
packages/react-magma-dom/src/components/Table/Table.tsx
packages/react-magma-dom/src/components/Table/TableRow.tsx
packages/react-magma-dom/src/i18n/default.ts
packages/react-magma-dom/src/i18n/interface.ts
website/react-magma-docs/src/pages/api/datagrid.mdx

Issue: #1384 #1383 
- Added `aria-live="polite"`
- Updated selectable datagrid to have unique labels for each checkbox
- Updated checkbox labels to update accordingly from "Select Row" to "Deselect Row" (each individual row and also the indeterminate one)
- Table Aria labels are now part of the i18n interface so they can be customized
- Updated examples in storybook and docs
- Test all datagrid examples in the docs site
- Test that the table component has not been affected
- Confirm that the appropriate aria labels are in place
- Confirm that the information is communicated correctly for screen readers when the pagination updated, or when items are selected

fix(DataGrid): Improved accessibility by adding `aria-live="polite"` and fixing labelText

---

.changeset/a11y-navTabs.md
packages/react-magma-dom/src/components/NavTabs/NavTab.tsx
packages/react-magma-dom/src/components/NavTabs/NavTabs.stories.tsx
website/react-magma-docs/src/pages/api/nav-tabs.mdx

Issue: #1238 
- Added `aria-current="page"` for active tabs
- Update `children` prop to not be required because they are not required for Icon only nav tabs, which we want to support
- Updated docs examples that were broken
- Added 2 more examples to storybook
Outstanding question: do we need aria-current for our regular tabs as well?
- Confirm new aria-current property for all nav tabs (custom and default)
- Confirm that NavTabs docs site is working as expected

fix(NavTabs): Improved accessibility by adding `aria-current="page"` for active tabs.

---

.changeset/a11y-loadingBtn.md
packages/react-magma-dom/src/components/Button/Button.stories.tsx
packages/react-magma-dom/src/components/Button/Button.test.js
packages/react-magma-dom/src/components/Spinner/index.tsx
packages/react-magma-dom/src/components/StyledButton/index.tsx
website/react-magma-docs/src/pages/api/button.mdx

Issue: #1398 
- Improved `isLoading` button example
- Removed Spinner role inside button when isLoading
- Added invisible span inside `isLoading` button that reads Loading
Confirm the isLoading state in all buttons (regular, icon)

fix(Button): Improved accessibility for `isLoading` button state

---

.changeset/emotion-update.md
website/react-magma-docs/src/pages/api-intro/changelog.mdx

Issue: #1411
We upgraded emotion but did not make it clear that this would require our adopters to upgrade their emotion versions. Adding it to our changelog
Confirm the information about upgrading emotion is visible in /api-intro/changelog/

docs: Update changelog text to alert adopters about the emotion update.

---

.changeset/fix-accordion-navigation.md
packages/react-magma-dom/src/components/Accordion/useAccordionButton.ts

Issue: #1385
We prevent default keyboard scroll behavior if some accordion header button are focused
- Open storybook accordion section
- Click on the first accordion header button
- Press on the keyboard 'Down' key
- Make sure scrollbar position on the page is not changed

fix(accordion): fix screen scroll behavior during accordion navigation

---

.changeset/a111y-breadCrumbs.md
packages/react-magma-dom/src/components/Breadcrumb/BreadcrumbItem.tsx
website/react-magma-docs/src/pages/api/breadcrumb.mdx

Issue: #1247
- Bug fix replace span with link to fix focus
1. Ensure each BreadcrumbItem is clickable when the to prop is provided.
2. Verify the last BreadcrumbItem is non-clickable, has aria-current="page", and can be focused.
3. Confirm the correct styles and focus behavior for both clickable and non-clickable items.

fix(BreadCrumb): replace span with link to fix focus

---

.changeset/a11y-datePicker-shortcut.md
packages/react-magma-dom/src/components/DatePicker/CalendarMonth.tsx
packages/react-magma-dom/src/components/DatePicker/DatePicker.test.js
packages/react-magma-dom/src/components/DatePicker/HelperInformation.tsx
packages/react-magma-dom/src/components/DatePicker/index.tsx
packages/react-magma-dom/src/components/DatePicker/utils.ts
packages/react-magma-dom/src/i18n/default.ts
packages/react-magma-dom/src/i18n/interface.ts
website/react-magma-docs/src/pages/api/internationalization.mdx

Issue: #1396
Change the shortcut on the DatePicker to open `HelperInformation` from `?` to `Ctrl+Shift+?`. Add a tooltip for it. Write test. Change localization.

fix(DatePicker): Remove the shortcut to open the `HelperInformation` component.

---

.changeset/inputwrapperstyles.md
packages/react-magma-dom/src/components/InputBase/index.tsx

Issue: none
Removed flex-shrink. We noticed that DatePicker had a min-width of 320px because of this, and it isn't needed.
This would affect:
- Input
- NativeSelect
- Select
- Textarea
- TimePicker
- DatePicker
- PasswordInput
- Search
- Combobox
Confirm that all of the components above continue to work as expected in all screen sizes and browsers.

fix(Input): Remove flex-shrink to allow inputs to shrink as needed

---

.changeset/fix-initial-expanded-items-should-expand-all-parents.md
packages/react-magma-dom/src/components/TreeView/TreeView.stories.tsx
packages/react-magma-dom/src/components/TreeView/TreeView.test.js
packages/react-magma-dom/src/components/TreeView/useTreeView.ts
packages/react-magma-dom/src/components/TreeView/utils.ts

Issue: #1431
Fixed initial expanded items should expand all parents
Storybook -> TreeView -> Complex example -> note that all parents of item 'Section 5.1: Apple pie apple pie tart macaroon topping chocolate cake' are expanded even if we list only this item but don't list parents inside 'initialExpandedItems' prop

fix(treeview): fix initial expanded items should expand all parents

---

.changeset/feat-success-button.md
packages/react-magma-dom/src/components/Button/Button.stories.tsx
packages/react-magma-dom/src/components/Button/index.tsx
packages/react-magma-dom/src/components/StyledButton/styles.ts
website/react-magma-docs/src/pages/api/button.mdx
website/react-magma-docs/src/pages/api/icon-button.mdx

Issue: #1296
The success button was added with all variations: solid/link and !isInverse/isInverse. Corrections were made to the documentation, and the icon version was added to the IconButton section.
1) Open the ButtonGroup page;
2) Select the success color.

feat(button): Add success button

---

.changeset/a11y-drawer-navigation-focus
.changeset/a11y-drawer-navigation-focus.md
packages/react-magma-dom/src/hooks/useFocusLock.ts

Issue: #1241
A filtering function was added to the `useFocusLock` hook, which filters out invisible elements that were being included in the `focusableItems.current` array and preventing the focus from being properly locked on the modal window.
1) Go to our documentation site.
2) Navigate to Components > Drawer
3) Click "Show Drawer" under "Navigation Example"
4) Tab through the opened Drawer

fix(drawer): Fix trapped focus in the drawer

---

.changeset/a11y-progressBar-animation.md
packages/react-magma-dom/src/components/ProgressBar/ProgressBar.test.js
packages/react-magma-dom/src/components/ProgressBar/index.tsx
packages/react-magma-dom/src/components/Select/SelectContainer.tsx
website/react-magma-docs/src/pages/api/progress-bar.mdx

Issue: #1242
Remove the animation if the user has a `prefers-reduced-motion` media query set.

fix(ProgressBar): Remove the animation if the user has a `prefers-reduced-motion` media query set.

---

.changeset/a11y-combobox-clear-focus.md
packages/react-magma-dom/src/components/Combobox/Combobox.tsx
packages/react-magma-dom/src/components/Combobox/MultiCombobox.tsx

Issue: #1234
After interacting with the clear button, the focus was returning to the container instead of the input field. The focus has been restored to the input for both the combobox and the multiselect combobox.
1. Navigate to Components > Combobox > Clearable
2. Tab to the input
3. Press Space bar and the panel of choices opens
4. Press Enter to select an option
5. Tab to the Clear button
6. Press Enter to clear the input
7. The Clear button disappears and the focus goes back to the input

fix(combobox): Fix focus issue after triggering the clear button

---

.changeset/a11y-docs-drawer-focus.md
packages/react-magma-dom/src/components/Drawer/Drawer.stories.tsx
website/react-magma-docs/src/pages/api/drawer.mdx

Issue: #1240
fix(drawer): Corrected examples for a `drawer` component to ensure focus returns to the opening button after the `drawer` closes.

fix(drawer): Fix focus return to the trigger button after the drawer closes

---

.changeset/feat-treeview-add-support-for-isdisabled.md
packages/react-magma-dom/src/components/TreeView/TreeItem.test.js
packages/react-magma-dom/src/components/TreeView/TreeItem.tsx
packages/react-magma-dom/src/components/TreeView/TreeView.stories.tsx
packages/react-magma-dom/src/components/TreeView/TreeView.test.js
packages/react-magma-dom/src/components/TreeView/TreeViewContext.ts
packages/react-magma-dom/src/components/TreeView/useTreeItem.ts
packages/react-magma-dom/src/components/TreeView/useTreeView.ts
packages/react-magma-dom/src/components/TreeView/utils.ts
website/react-magma-docs/src/pages/api/tree-view.mdx

Issue: #1305
New feature: add support `isDisabled` prop for TreeView to disable all items
New feature: add support `isDisabled` field for items of `preselectedItems` prop to manage disabled state for items
Storybook > TreeView > Complex:
We can see that item 'Section 5.1.2' is disabled by setting `isDisabled` to true via  preselectedItems
We can switch TreeView's `isDisabled` prop to true to disable all items

feat(treeview): add support for isDisabled

---

.changeset/a11y-datePicker-nav-issues.md
packages/react-magma-dom/src/components/DatePicker/CalendarContext.ts
packages/react-magma-dom/src/components/DatePicker/CalendarMonth.tsx
packages/react-magma-dom/src/components/DatePicker/DatePicker.test.js
packages/react-magma-dom/src/components/DatePicker/HelperInformation.test.js
packages/react-magma-dom/src/components/DatePicker/HelperInformation.tsx
packages/react-magma-dom/src/components/DatePicker/index.tsx
packages/react-magma-dom/src/i18n/default.ts

Issue: #1080
This problem is related to the operation of the NVDA screen reader. Users with this screen reader must change the NVDA mode to `focus` to properly interact with the calendar. Added additional text to the `calendarOpenAnnounce` label.
Fix navigation and accessibility issues.
**Previous behavior:** 
- Open `DatePicker` -> Open `HelperInformation` -> Press `Tab` several times -> Focus outside `HelperInformation`.
- Open `DatePicker` -> Open `HelperInformation` -> Return back to `DatePicker` -> Press `Tab` several times -> Focus outside `DatePicker`.
**Current behavior:**
- Open `DatePicker` -> Open `HelperInformation` -> Press `Tab` several times -> Focus inside `HelperInformation`.
- Open `DatePicker` -> Open `HelperInformation` -> Return back to `DatePicker` -> Press `Tab` …

fix(DatePicker): Fix navigation and accessibility issues.

---

.changeset/fix-input-focus-outline.md
packages/react-magma-dom/src/components/Combobox/ComboboxInput.tsx
packages/react-magma-dom/src/components/InputBase/index.tsx
packages/react-magma-dom/src/theme/GlobalStyles/index.tsx

Issue: #1294 
update focus outline offset on inputs to -1px 
confirm that Inputs have -1px border outline when focused instead of 2px
- Text field
- Text area
- Number
- Date
- Time
- Search
- Password
- Select
- Native select
- Combobox

fix(Input): Style update: Focus style on inputs.

---

.changeset/feat-progressBar-update-colors.md
packages/react-magma-dom/src/components/ProgressBar/ProgressBar.test.js
packages/react-magma-dom/src/components/ProgressBar/index.tsx

Issue: #1424
Update colors from danger200/success200 to danger300/success300 in dark mode.
Open `ProgressBar` -> Set dark mode (`isInverse` prop) -> Set custom `danger` or `success` color -> Check `ProgressBar`'s color.

feat(ProgressBar): Update colors from danger200/success200 to danger300/success300 in dark mode.

---

.changeset/fix-toast-loading-ring-misaligned.md
packages/react-magma-dom/src/components/ProgressRing/index.tsx

Issue: #1265
Fixed loading ring alignment when zooming in Safari.
Open Toast in docs/storybook -> Change viewport in Safari (Zoom in or zoom out) -> Click the button to Toast -> Make sure the loading ring is in the correct position.

fix(Toast): Fixed loading ring alignment when zooming in Safari.

---

.changeset/chore-deprecate-header.md
.changeset/chore-deprecate-schema.md
packages/schema-renderer/README.md
patterns/header/README.md
website/react-magma-docs/src/pages/api/schema-renderer.mdx
website/react-magma-docs/src/pages/patterns/header.mdx

Issue: #1498
Deprecate 2 unused packages:
- Marked as deprecated on README
- Added an alert on the docs site
- Deprecated them on npmjs
In addition, there were a few other old magma packages that have hung around for a while that we don't even have the source code for, so I marked those as deprecated on NPM as well.
--
Confirm on NPM js + docs site.

Deprecate schema-renderer and header patterns

---

.changeset/fix-tabs-center-active-tab.md
packages/react-magma-dom/src/components/NavTabs/NavTabs.stories.tsx
packages/react-magma-dom/src/components/NavTabs/NavTabs.tsx
packages/react-magma-dom/src/components/Tabs/Tabs.stories.tsx
packages/react-magma-dom/src/components/Tabs/Tabs.tsx

Issue: #1481
Center preselected `Tab` on the `Scrollable Tabs`.
Open `Scrollable Tabs` -> Preselect active `Tab` using the `activeIndex` property -> Check that it is centered.

fix(Tabs): Center preselected `Tab` on the `Scrollable Tabs`.

---

.changeset/a11y-breadcrumb-hide-svg-from-screen-readers.md
packages/react-magma-dom/src/components/Breadcrumb/Breadcrumb.test.js
packages/react-magma-dom/src/components/Breadcrumb/BreadcrumbItem.tsx

Issue: #1248
Hide SVGs from screen readers by adding `aria-hidden="true"` to the `span` element that wraps the SVGs.
Open `Breadcrumb` -> Open DevTools -> Check styles.

fix(Breadcrumb): Hide SVGs from screen readers by adding `aria-hidden="true"` to the `span` element that wraps the SVGs.

---

.changeset/a11y-checkbox-hide-svg-from-screen-readers.md
packages/react-magma-dom/src/components/Checkbox/Checkbox.test.js
packages/react-magma-dom/src/components/Checkbox/index.tsx
packages/react-magma-dom/src/components/IndeterminateCheckbox/IndeterminateCheckbox.test.js
packages/react-magma-dom/src/components/IndeterminateCheckbox/index.tsx

Issue: #1249
Hide SVGs from screen readers by adding `aria-hidden="true"` to the `span` element that wraps the SVGs.
Open `Checkbox` -> Open DevTools -> Check styles.

fix(CheckBox): Hide SVGs from screen readers by adding `aria-hidden="true"` to the `span` element that wraps the SVGs.

---

.changeset/a11y-list-hide-icons-from-assistive-tech.md
packages/react-magma-dom/src/components/List/List.test.js
packages/react-magma-dom/src/components/List/ListItem.tsx

Issue: #1244
Hide SVGs from assistive tech by adding `aria-hidden="true"` to the `span` element that wraps the SVGs.
Open `List with icons` -> Open DevTools -> Check styles.

fix(List): Hide SVGs from assistive tech by adding `aria-hidden="true"` to the `span` element that wraps the SVGs.

---

.changeset/a11y-dropdown-hide-svg-from-screen-readers.md
packages/react-magma-dom/src/components/Alert/__snapshots__/Alert.test.js.snap
packages/react-magma-dom/src/components/ButtonGroup/__snapshots__/ButtonGroup.test.js.snap
packages/react-magma-dom/src/components/Dropdown/Dropdown.test.js
packages/react-magma-dom/src/components/Dropdown/DropdownButton.tsx
packages/react-magma-dom/src/components/Dropdown/DropdownSplitButton.tsx
packages/react-magma-dom/src/components/IconButton/__snapshots__/IconButton.test.js.snap
packages/react-magma-dom/src/components/IconButton/index.tsx

Issue: #1250
Hide SVGs from screen readers by adding `aria-hidden="true"` to the `svg` elements.
Open `Dropdown` -> Open DevTools -> Check styles.

fix(Dropdown): Hide SVGs from screen readers by adding `aria-hidden="true"` to the `svg` elements.

---

.changeset/docs-emotion.md
website/react-magma-docs/src/pages/api-intro/changelog.mdx

Issue: -
I received a message from a team having issues with upgrading from 4.3.0 to 4.6.0. Turns out they were using the emotion `css` prop, and that's not working for them anymore
```
const bodyStyle = css`
padding: 16px 16px 0 16px;
`;
return (
<Card
css={cardCss}
background={theme.colors.neutral600}
isInverse
>
<CardBody css={bodyStyle}>
...
```
Turns out that with the latest version of emotion that we upgraded to, that is no longer supported. These are the supported ways of styling components:
https://codesandbox.io/p/sandbox/emotion-11-and-magma-2tg5w5?file=%2Fexample.tsx
This PR just makes a note in the changeset for adopters to be aware of this.

docs: Update changelog to explain possible issue with emotion/css.

---

.changeset/fix-select-combobox-multi-outline.md
packages/react-magma-dom/src/components/Select/shared.ts

Issue: #1499
change outline offset on Combobox and Select selected items
check the outline on selected items in 
- /story/select--multi
- /story/combobox--multi

fix(Select) Multi Select and Multi Combobox selected item focus outline

---

.changeset/feat-treeview-onexpandedchange.md
packages/react-magma-dom/src/components/TreeView/TreeItem.tsx
packages/react-magma-dom/src/components/TreeView/TreeView.stories.tsx
packages/react-magma-dom/src/components/TreeView/TreeViewContext.ts
packages/react-magma-dom/src/components/TreeView/useTreeView.ts
packages/react-magma-dom/src/components/TreeView/utils.ts
website/react-magma-docs/src/pages/api/tree-view.mdx

Issue: #1499
- Implemented functionality for onExpandedChange to return an array of expanded items similar to how onSelectedItemChange returns selected items. 
test the implementation example in 
- storybook: /treeview--complex
- documentation: api/tree-view/#change_events

feat(TreeView): onExpandedChange returns an array of expanded IDs

---

.changeset/treeview-undefined-3.md
packages/react-magma-dom/src/components/TreeView/useTreeView.ts
packages/react-magma-dom/src/components/TreeView/utils.ts

Issue: none
MAST is reporting running into `Error: Uncaught [TypeError: Cannot read properties of undefined (reading 'hasOwnTreeItems')]` in our pre-release version. Adding null checking to a few more places to see if that fixes is.
Can't reproduce this issue locally, so will merge and send to MAST team to test.

fix(TreeView): Fix undefined problem

---

.changeset/heading-margins.md
packages/react-magma-dom/src/components/Heading/Heading.test.js
packages/react-magma-dom/src/components/Heading/__snapshots__/Heading.test.js.snap
packages/react-magma-dom/src/components/Typography/index.tsx

Issue: #1555 
- Update margins for heading2XLarge
- Fix headingLarge + noBottomMargin (it was adding top margin it never had)
Before:
After:
- Navigate to https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/heading--default
- Confirm the expected margins for heading2XLarge + headingXLarge while switching on and off the noMargins, noTopMargin and noBottomMargin props

fix(Heading): Update margins for `heading2XLarge`

---

.changeset/selecteItemButton-focus.md
packages/react-magma-dom/src/components/Select/shared.ts

Issue: #1559
Fix focus color for `isInverse`
Before:
After:
Confirm focus styles in:
- Combobox: https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/combobox--inverse&args=isMulti:true
- Select: https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/select--inverse&args=isMulti:true

fix(Combobox/Select:): Fix focus color for selected items when using `isMulti` + `isInverse`

---

.changeset/tag-focus.md
packages/react-magma-dom/src/components/Tag/Tag.stories.tsx
packages/react-magma-dom/src/components/Tag/Tag.test.js
packages/react-magma-dom/src/components/Tag/Tag.tsx

Issue: none
I noticed that clickable and deletable tags had been accidentally updated to have the offset of `-1`, so I updated them to have the correct `2px` offset, and also to use the correct focus color. While I was there, I updated the stories on storybook to be less repetitive and added unit tests.
Before:
After:
Navigate to storybook and ensure that clickable tags have the expected focus state for both isInverse and default. Also ensure the other tags don't get a focus state.

fix(Tag): Update tag focus state

---

.changeset/tree-validity.md
packages/react-magma-dom/src/components/TreeView/TreeView.stories.tsx
packages/react-magma-dom/src/components/TreeView/TreeView.test.js
packages/react-magma-dom/src/components/TreeView/utils.ts

Issue: none
MAST engineers reported a change in behavior from `4.6.0` to our prerelease. Items that had invalid children would get the expandable arrow when they shouldn't. In addition, I added unit tests so we don't break this accidentally in the future.
All examples with the same code:
```
<TreeView>
<TreeItem label="Node 0 - fragment" itemId="item0" testId="item0">
<></>
</TreeItem>
<TreeItem label="Node 1" itemId="item1" testId="item1">
<TreeItem label="Child 1" itemId="item-child1">
<TreeItem label="Grandchild 1" itemId="item-gchild1">
<Tag>This is a tag as a child of Grandchild 1</Tag>
</TreeItem>
</TreeItem>
</TreeItem>
<TreeItem label="Node 2" itemId="item2">
<TreeItem label="Child 2" itemId="item-child2">
<TreeItem label="Grandchild 2" itemId="item-gchild2">
<TreeItem …
```

fix(TreeView): Fix invalid tree item children

---

.changeset/fix-docs-examples.md
website/react-magma-docs/src/components/ButtonProps/index.js
website/react-magma-docs/src/components/IconButtonProps/index.js
website/react-magma-docs/src/pages/api/accordion.mdx
website/react-magma-docs/src/pages/api/checkboxes.mdx
website/react-magma-docs/src/pages/api/combobox.mdx
website/react-magma-docs/src/pages/api/container.mdx
website/react-magma-docs/src/pages/api/date-pickers.mdx
website/react-magma-docs/src/pages/api/dropdown.mdx
website/react-magma-docs/src/pages/api/form.mdx
website/react-magma-docs/src/pages/api/formgroup.mdx
website/react-magma-docs/src/pages/api/grid.mdx
website/react-magma-docs/src/pages/api/hyperlink.mdx
website/react-magma-docs/src/pages/api/icon-button.mdx
website/react-magma-docs/src/pages/api/radio.mdx
website/react-magma-docs/src/pages/api/select.mdx
website/react-magma-docs/src/pages/api/stepper.mdx
website/react-magma-docs/src/pages/api/toast.mdx
website/react-magma-docs/src/pages/api/toggle.mdx
website/react-magma-docs/src/pages/api/use-focus-lock.mdx
website/react-magma-docs/src/pages/design/progress-bar.mdx

Issue: # [1554](https://github.com/cengage/react-magma/issues/1554)
Cleaned up CodeSandbox examples for: **Grid, Container, Stepper, Combobox, Hyperlink, IconButton, Toast, DatePicker, Dropdown, Form, FormGroup, & useFocusLock**
Go to: https://next--upbeat-sinoussi-f675aa.netlify.app/api/
**1. Grid**
Basic Usage example
**2. Container**
All examples
**3. Stepper**
Step label example
Completed Step Description example
**4. Combobox**
Label Position example
Async example
Custom Items example
**5. Hyperlink**
Icon example
**6. IconButton**
Basic Usage example
Inverse example
**7. Toast**
Toast Documentation
There are a couple items in the "Accessibility Considerations" section that need to be fixed.
The toast …

FIxes > Various Docs site issues

---

.changeset/feat-select-disabled-items.md
packages/react-magma-dom/src/components/Select/ItemsList.tsx
packages/react-magma-dom/src/components/Select/MultiSelect.test.js
packages/react-magma-dom/src/components/Select/MultiSelect.tsx
packages/react-magma-dom/src/components/Select/Select.stories.tsx
packages/react-magma-dom/src/components/Select/Select.test.js
packages/react-magma-dom/src/components/Select/Select.tsx
packages/react-magma-dom/src/components/Select/components.tsx
packages/react-magma-dom/src/components/Select/index.tsx
packages/react-magma-dom/src/components/Select/shared.ts
packages/react-magma-dom/src/components/Select/utils.ts
website/react-magma-docs/src/pages/api/select.mdx

Issue: #1217 
- added support for disabling individual items in react-magma-dom
- added a unit test for that behavior 
- added an example in the docs under api/select#disabled_items
check behavior in storybooks and in docs under api/select#disabled_items

feat(Select): Support disabling individual items

---

.changeset/fix-GlobalStyles-import-warning.md
packages/react-magma-dom/src/theme/GlobalStyles/index.tsx

Issue: #1604
* moved font import to a separate `Global` 
* update the font import link from google fonts
from **[emotion docs](https://emotion.sh/docs/emotion-11#stylis-v4)** 
> @import rules are no longer special-cased. The responsibility to put them first has been moved to the author of the styles. They also can't be nested within other rules now. It's only possible to write them at the top level of global styles.
navigate to 
https://docs-preview-1607--upbeat-sinoussi-f675aa.netlify.app/api/global-styles/
check console for the `@import` warning

fix @import rule warning in GlobalStyles

---

.changeset/fix-FormGroup-input-message.md
packages/react-magma-dom/src/components/FormGroup/FormGroup.test.js
packages/react-magma-dom/src/components/FormGroup/index.tsx

Issue: #
Validation for `InputMessage` in `FormGroup` created an empty container when there was no message. Fixed this validation.

fix(FormGroup): Fix validation for `InputMessage`

---

.changeset/fix-tableOverflow.md
packages/react-magma-dom/src/components/Table/Table.stories.tsx
packages/react-magma-dom/src/components/Table/Table.test.js
packages/react-magma-dom/src/components/Table/Table.tsx
packages/react-magma-dom/src/components/Table/TableCell.tsx
packages/react-magma-dom/src/components/Table/TableHeaderCell.tsx
packages/react-magma-dom/src/components/Table/TableRow.tsx

Issue: # [1556](https://github.com/cengage/react-magma/issues/1556)
- Corrected CSS that was limiting dropdowns and other such UI elements that were being clipped within the `Table` container.
- Head over to Storybook
- Table example > With Dropdown
- Click any of the dropdowns to verify they extend outside of the container appropriately

fix(Table): Reconfigured the table CSS to better allow for content within a table to overlay the container, such as dropdowns.

---

.changeset/fix-TablePagination-NativeSelect-rowsPerPage.md
packages/react-magma-dom/src/components/Datagrid/Datagrid.test.js
packages/react-magma-dom/src/components/Table/Table.stories.tsx
packages/react-magma-dom/src/components/Table/TablePagination.tsx

Closes: #1599
Fix logic for the default rowsPerPage value.
1. **Controlled Pagination**: 
- Open Storybook -> Table -> Controlled Pagination -> Select `rowsPerPage` that includes in the `rowsPerPageValues` array -> See that table shows the selected rows per page;
- Open Storybook -> Table -> Controlled Pagination -> Select `rowsPerPage` that DOESN'T include in the `rowsPerPageValues` array -> See that table shows the first number of `rowsPerPageValues` array.
2. **Uncontrolled Pagination**:
- Open Storybook -> Table -> Uncontrolled Pagination -> Select `defaultRowsPerPage` that includes in the `rowsPerPageValues` array -> See that table shows the selected rows per page;
- Open Storybook -> Table -> Controlled Pagination -> Select `rowsPerPage` that DOESN'T include in the …

fix(Table): fix logic for the default rowsPerPage value.

---

.changeset/fix-DatePicker-input-wrong-number.md
packages/react-magma-dom/src/components/TimePicker/TimePicker.test.js
packages/react-magma-dom/src/components/TimePicker/TimePicker.tsx
packages/react-magma-dom/src/components/TimePicker/useTimePicker.ts

Issue: #1517 
Fix TimePicker validation.
- Open Storybook -> TimePicker -> Replace the time with '11:59' -> Try replacing the minutes from 59 to 30 by pressing the number 3 when the minutes are selected, then 0 -> Notice that the time ends up being '30'. 
- Same for Hours -> '11:59' -> Replacing from 11 to 9 -> Notice that the time ends up being '9'.

fix(TimePicker): Fix input wrong number validation

---

.changeset/fix-Toast-close-button-announced-twice.md
packages/react-magma-dom/src/components/AlertBase/index.tsx
packages/react-magma-dom/src/components/Toast/Toast.stories.tsx
website/react-magma-docs/src/pages/api/toast.mdx

Issue: #1606
Change property for Toast from `aria-label` to `title`.  
Add clarification in the documentation that developers should use the `Announce` component with `Toast`.
Open Storybook -> Toast -> Enable ScreenReader/VoiceOver -> Click on `Show Toast` -> Make sure screenreader works as expected.

fix(Toast): Change property for Toast from `aria-label` to `title`.

---

.changeset/fix-AppBar.md
packages/react-magma-dom/src/components/AppBar/AppBar.stories.tsx
packages/react-magma-dom/src/components/SkipLink/__snapshots__/SkipLink.test.js.snap
packages/react-magma-dom/src/components/SkipLink/index.tsx
website/react-magma-docs/src/pages/api/skip-link.mdx

Closes: #1654 
- Added CSS property to ensure the `SkipLink` component properly displays above the `AppBar` when both are used.
- Added Doc / Storybook examples under `AppBar` to highlight the proper interaction.
- [N/A] New and existing unit tests pass locally with the proposed changes
- [N/A] Tests that prove the fix is effective or that the feature works have been added
Go to Docs / Storybook `AppBar` example > Press tab > Verify `SkipLink` appears above `AppBar`.

fix(SkipLink): Fix overlap with the SkipLink component when used with AppBar.

---

.changeset/simple-pag.md
packages/react-magma-dom/src/components/Pagination/Pagination.stories.tsx
packages/react-magma-dom/src/components/Pagination/SimplePagination.test.js
packages/react-magma-dom/src/components/Pagination/SimplePagination.tsx
website/react-magma-docs/src/pages/api/pagination.mdx

Closes: #1662
- Added support for `page` prop
N/A
- Use the `page` prop in simple pagination and ensure it updates appropriately
- Use the `defaultPage` prop in simple pagination and ensure it still behaves as expected (this requires a page refresh by design)
- Confirm that when using both `page` and `defaultPage`, `page` takes precedence
- Confirm that navigating with the arrows works when using page, defaultPage or both props together

fix(Pagination): Fix support for `page` in SimplePagination

---

.changeset/fix-Password-input-password-manager.md
packages/react-magma-dom/src/components/Input/Input.test.js
packages/react-magma-dom/src/components/InputBase/index.tsx
packages/react-magma-dom/src/components/PasswordInput/PasswordInput.test.js

Closes: #1165
Fix webkit styles for the `PasswordInput` when using the password manager
Open Storybook/Docs -> PasswordInput -> Select password from the password manager -> Check styles.

fix(password input): fix webkit styles when using the password manager

---

.changeset/feat-Input-new-types.md
packages/react-magma-dom/src/components/Input/Input.stories.tsx
packages/react-magma-dom/src/components/Input/Input.test.js
packages/react-magma-dom/src/components/InputBase/index.tsx
website/react-magma-docs/src/pages/api/input.mdx

Closes: #1689
- Added new types `tel` and `url` for Input component.
- Updated storybook and react-magma-docs.
- Go to Input -> Phone Input or Url Input
- Fill out the Input related a pattern for a phone number or Url

feat(Input): Support new types: `tel` and `url`

---

.changeset/fix-Search-Update-icon-styles.md
packages/react-magma-dom/src/components/InputBase/index.tsx
packages/react-magma-dom/src/components/Search/Search.stories.tsx

Closes: #1575 
- Updated `clear` button styles for `Search` component 
- Add some examples in Storybook
Storybook
- Go to Search -> Clearable -> type some text in input -> the focus border of `clear` button shouldn't be on the `search icon`
- Go to Search -> Large -> type some text in input -> the focus border of `clear` button shouldn't be on the `search icon`

fix(Search): Style issues with clear and search icons

---

.changeset/fix-Dropdown-add-icon-parent-level.md
packages/react-magma-dom/src/components/Dropdown/Dropdown.stories.tsx
packages/react-magma-dom/src/components/Dropdown/DropdownExpandableMenuListItem.tsx

Closes: #1573
- Added the `icon` prop for `DropdownExpandableMenuListItem` component.
React Magma Docs
Storybook
- Go to `Storybook`
- Open Dropdown -> Dropdown Expandable Menu List Item With Icons :
- for Specialty Pizza -> Capricciossa -> should be invisible icon (because is inside list of items)
- for Cheese Pizza -> should be visible icon

fix(Dropdown): Expandable Menu Items > Icon missing at parent level

---

.changeset/fix-Modal-closing-slow.md
packages/react-magma-dom/src/components/Modal/Modal.tsx

Closes: #1522
- Delete timeout for closing modal
[Screencast from 26.03.25 10:51:04.webm](https://github.com/user-attachments/assets/3e47dfe1-8572-4b43-b819-9cab20ee43d1)
- Go to **Storybook**
- Open Modal -> Default -> Click on **Show Modal** button and click on **X** button
- Closing of Modal should be without any latency

fix(Modal): Closing modals is slow

---

.changeset/fix-Tabs-Improve-functionality-small-screen.md
packages/react-magma-dom/src/components/Tabs/TabsScrollSpyContainer.tsx
packages/react-magma-dom/src/components/Tabs/utils.ts

Closes: #1562
- Improved scrolling functionality for small screens
- Fixed selecting last tab the user scrolls to the bottom of the page
[Screencast from 27.03.25 14:35:06.webm](https://github.com/user-attachments/assets/8e7242d8-a806-480b-a5f6-eaa055a2038d)
[Screencast from 27.03.25 14:30:36.webm](https://github.com/user-attachments/assets/c5d8ff0b-380b-45ea-bb82-65b6c954cca8)
[Screencast from 27.03.25 12:37:31.webm](https://github.com/user-attachments/assets/5262023c-bd26-4153-bacd-3f5a320fc035)
- Go to Tabs -> ScrollSpy/Scroll Spy Icons -> zoom to 300% -> scroll down -> the tabs on the left side should update as soon as you start scrolling into a new section.
- Compress your browser window and scroll down ->  the tabs on the left side should update as soon as you start …

fix(tabs): improve scroll functionality for smaller screens

---

.changeset/update-ladning-page.md
website/react-magma-landing/scripts/build.js
website/react-magma-landing/templates/_redirects

Closes: #1716 
- Added proxy redirect for version 2.6.0 to serve content from https://soft-elf-84cb2b.netlify.app/
- Updated the landing page build script to only support specific legacy versions [2.6.0, 3.10.0, 3.11.0] and all v4.x 
1. Build the landing page locally: 
```
cd website/react-magma-landing && npm run build
```
2. Verify that the generated `_redirects` file in the `dist` directory contains the proper redirect for version 2.6.0:
```
/version/2.6.0/* https://soft-elf-84cb2b.netlify.app/:splat 200
```
3. Verify that the version list only includes v4.x versions and the specified legacy versions [2.6.0, 3.10.0, 3.11.0]:
```
cat dist/versions
```
4. After deployment, verify that navigating to `https://react-magma.cengage.com/version/2.6.0/` displays content from the legacy site …

chore(docs): update landing page

---

.changeset/fix-Dropdown-not-displayed-above-elements.md
packages/react-magma-dom/src/components/ButtonGroup/__snapshots__/ButtonGroup.test.js.snap
packages/react-magma-dom/src/components/Dropdown/Dropdown.test.js
packages/react-magma-dom/src/components/Dropdown/DropdownContent.tsx

Closes: #1737
- Updated the z-index value for `DropdownContent` to ensure it is displayed above all other elements.
- Added test and updated snapshot.
- To verify it, you need to add some content for Dropdown into storybook.
- Go to storybook -> Dropdown -> get your updated example ->  DropdownContent should be displayed above all suggested components.

fix(Dropdown): Displaying dropdown content under other elements.

---

.changeset/fix-SkipLink-deprecate-to-prop.md
packages/react-magma-dom/src/components/SkipLink/index.tsx

Closes: #1744
- Add `to` prop as an option for the `SkipLink`  component.
- Added comment that this prop is deprecated and will be removed in the next major release.
- Go to React Magma Dom
- Open SkipLink component
- The prop `to` should be available for use as an optional
- In comments should be marked as deprecated and informed about being fully deleted in the next major release.

fix(SkipLink): Deprecate `to` prop.

---

.changeset/chore-Remove-old-doc-links.md
website/react-magma-docs/src/pages/api-intro/versions.mdx

Closes: #1750
Removed all old docs links less than 4.0.0.
Updated description of React Magma Versions page.
[Screencast from 06.05.25 17:37:41.webm](https://github.com/user-attachments/assets/4e13db2a-ae1f-4025-99d0-b27a4bd9f517)
-> Go to React Magma Docs
-> Components -> Intro -> React Magma Versions
-> Released Versions -> Doc links should be unavailable for versions earlier than 4.0.0
-> Released Versions -> Doc links should be available for versions older than 4.0.0

chore: Update React Magma Versions page to remove old docs link.

---

.changeset/feat-multiselect-new-option-disabled.md
packages/react-magma-dom/src/components/Select/MultiSelect.test.js
packages/react-magma-dom/src/components/Select/MultiSelect.tsx
packages/react-magma-dom/src/components/Select/Select.stories.tsx

Closes: #1202
Make selected items disabled when MultiSelect is disabled
Open StoryBook -> MultiSelect -> Select a few items -> Turn on the `disabled` option.

feat(MultiSelect): Make selected items disabled when MultiSelect is disabled

---

.changeset/feat-Dropdown-Add-leading-icon.md
packages/react-magma-dom/src/components/ButtonGroup/__snapshots__/ButtonGroup.test.js.snap
packages/react-magma-dom/src/components/Dropdown/Dropdown.stories.tsx
packages/react-magma-dom/src/components/Dropdown/Dropdown.test.js
packages/react-magma-dom/src/components/Dropdown/Dropdown.tsx
packages/react-magma-dom/src/components/Dropdown/DropdownButton.tsx
packages/react-magma-dom/src/components/IconButton/IconButton.stories.tsx
packages/react-magma-dom/src/components/IconButton/IconButton.test.js
packages/react-magma-dom/src/components/IconButton/__snapshots__/IconButton.test.js.snap
packages/react-magma-dom/src/components/IconButton/index.tsx
website/react-magma-docs/src/components/IconButtonProps/index.js
website/react-magma-docs/src/pages/api/dropdown.mdx
website/react-magma-docs/src/pages/api/icon-button.mdx

Closes: #1745 
- Added the new `leadingIcon` prop for `DropdownButton` and `IconButton`
- Updated React Magma docs for these components
- Added some new unit tests
- Added examples in docs and storybook
**Storybook:**
**React Magma Docs:**
**Dropdown Button:**
- Go to Storybook
- DropDown -> Leading Icon
- All styles should be the same as in these [mock-ups](https://www.figma.com/design/VoWYiiOKKppcYm5QLgPyDC/Components---Inputs?m=auto&node-id=2506-3713&t=ibAT74oQ5OxMb9zC-1)
- Go to React Magma Docs
- Components -> Dropdown -> Leading Icon
- The description and an example of this new prop should be provided
- The documentation of `Dropdown button props` should be updated
**Icon Button:**
- Go to Storybook
- Icon Button -> Leading Icon
- All styles should be the same as in these …

feat(DropdownButton): Add leading icon capability

---

.changeset/fix-Input-not-properly-update-value.md
packages/react-magma-dom/src/components/Input/Input.stories.tsx
packages/react-magma-dom/src/components/Input/Input.test.js
packages/react-magma-dom/src/components/Input/testUtils.tsx
packages/react-magma-dom/src/components/InputBase/index.tsx

Closes: #[1721](https://github.com/cengage/react-magma/issues/1721)
- Provided a fix for this issue on the customer side.
- Added example in Storybook.
- Added additional tests of using `Input` on the customer side to track break changes.
[Screencast from 11.04.25 10:50:08.webm](https://github.com/user-attachments/assets/e12404ca-caea-41db-9014-60a3f96b502c)
Storybook:
- Go to Storybook
- Input -> Time Input
- Type 133, 66 or 333 into the `Minutes` field (RM input)
- In case of 66, in **Hours** field should be `1` hour and in **Minutes** should be `6`
- The values of minutes and hours have to be the same for the native input component.
**On the customer side need add this line to fix this issue:**
`isHours ? setHours(currentUnitValue) : setMinutes(currentUnitValue);`
You can take a look …

fix(Input): Does not update value as expected

---

.changeset/chore-docs-add-warning-for-tooltip.md
website/react-magma-docs/src/pages/api/tooltip.mdx

Closes: #1802 
Add warning for `Tooltip` that the child element must be able to accept a ref.
Open docs -> Tooltip -> Basic Usage -> Check Warning

chore(docs): Add warning for `Tooltip` that the child element must be able to accept a ref.

---

.changeset/feat-Toogle-remove-animation.md
packages/react-magma-dom/src/components/Toggle/Toggle.test.js
packages/react-magma-dom/src/components/Toggle/index.tsx

Closes: #1552 
- Removed animation for Toggle.
Go to Storybook -> Toggle -> Default -> Click on `Toggle label off` -> the animation is not shown

feat(Toggle): Remove part of the animation

---

.changeset/feat-Button-update-icon-size.md
packages/react-magma-dom/src/components/ButtonGroup/ButtonGroup.test.js
packages/react-magma-dom/src/components/ButtonGroup/__snapshots__/ButtonGroup.test.js.snap
packages/react-magma-dom/src/components/ButtonGroup/index.tsx
packages/react-magma-dom/src/components/Dropdown/Dropdown.test.js
packages/react-magma-dom/src/components/Dropdown/DropdownSplitButton.tsx
packages/react-magma-dom/src/components/IconButton/IconButton.stories.tsx
packages/react-magma-dom/src/components/IconButton/IconButton.test.js
packages/react-magma-dom/src/components/IconButton/__snapshots__/IconButton.test.js.snap
packages/react-magma-dom/src/components/IconButton/index.tsx
packages/react-magma-dom/src/components/ToggleButton/ToggleButton.test.js
packages/react-magma-dom/src/components/ToggleButton/ToggleButton.tsx
packages/react-magma-dom/src/components/TreeView/__snapshots__/TreeView.test.js.snap

Closes: #1738
**Update icon size for buttons:**
- Icon button
- Dropdown button
- Button group
- Toggle button
For all icons should be:
Large = **24px**
Medium = **20px**
Small = **16px**
Go to `Storybook` -> `ToogleButton` -> Icon 
Go to `Storybook` -> `ToogleButtonGroup` -> Default
Go to `Storybook` -> `IconButton` -> Default
Go to `Storybook` -> `ButtonGroup` -> Default
Go to `Storybook` -> `Dropdown` -> Leading Icon

feat(ButtonGroup, IconButton, ToogleButton): Update icon size on all button and button-based componets.

---

.changeset/fix-Table-incorrect-pagination.md
packages/react-magma-dom/src/components/Datagrid/Datagrid.test.js
packages/react-magma-dom/src/components/Table/TablePagination.test.js
packages/react-magma-dom/src/components/Table/TablePagination.tsx

Closes: #1843 
- Fixed incorrect table pagination
Go to **Storybook** -> **Table** -> **Controlled** Pagination:
Change rows per page from **10** to **20** and then back to **10** -> The actual rows are **11-20**.

fix(Table): Incorrect Pagination behavior

---

.changeset/feat-Popover-support-programmatically-opening.md
packages/react-magma-dom/src/components/Popover/Popover.stories.tsx
packages/react-magma-dom/src/components/Popover/Popover.test.js
packages/react-magma-dom/src/components/Popover/Popover.tsx
website/react-magma-docs/src/pages/api/popover.mdx

Closes: #1853 
Added supporting `Popover` programmatically opening.
Go to Storybook -> `Popover` -> `Programatically Opening` -> Focus on text -> Press `Enter` or `Space` -> Popover should be opened
Go to React Magma Docs -> `Components` -> `Popover` -> `Controlled Popover via with API ref` -> The  `openPopoverManually` API should be added to the example -> click on `Open Popover` button -> `Popover` should be opened

feat(Popover):  Support programmatically opening

---

.changeset/feat-Treeview-add-styles-customixation.support.md
packages/react-magma-dom/src/components/TreeView/TreeItem.test.js
packages/react-magma-dom/src/components/TreeView/TreeItem.tsx
packages/react-magma-dom/src/components/TreeView/TreeView.stories.tsx
packages/react-magma-dom/src/components/TreeView/TreeView.test.js
packages/react-magma-dom/src/components/TreeView/TreeViewContext.ts
packages/react-magma-dom/src/components/TreeView/__snapshots__/TreeView.test.js.snap
packages/react-magma-dom/src/components/TreeView/useTreeItem.ts
packages/react-magma-dom/src/components/TreeView/useTreeView.ts

Closes: #1839 
- Added new prop for `TreeView`: **expandIconStyles** 
- Added new props for `TreeItem`:  **hoverColor** and **treeItemStyles**
Open Storybook -> Treeview -> **Open Custom Expand Icon Arrow And TreeItem Styles:**
1. `Mammals` should have a custom background and hover color
2. `Amphibians`should have a custom background color

feat(TreeView): Add styles customization support

---

.changeset/feat-Popover-alignment-prop-custom-width.md
packages/react-magma-dom/src/components/Popover/Popover.stories.tsx
packages/react-magma-dom/src/components/Popover/Popover.test.js
packages/react-magma-dom/src/components/Popover/Popover.tsx
packages/react-magma-dom/src/components/Popover/PopoverContent.tsx
packages/react-magma-dom/src/components/Popover/__snapshots__/Popover.test.js.snap
packages/react-magma-dom/src/index.ts
website/react-magma-docs/src/pages/api/popover.mdx

Closes: #1820 
- Added the new `alignment` prop
- Deleted hardcoded `max-width` for customizing
- Updated docs with additional examples.
`Storybook` -> `Popover` -> `Default` -> pass in the control panel different options of `alignment` -> should align `PopoverContent` according to the passed option.
`React Magma Docs` -> Components -> Popover -> `Popover Alignment` -> should be added new example with description of new prop
`React Magma Docs` -> Components -> Popover -> `Popover Props` -> should be added documentation about new prop.

feat(Popover): Support alignment prop & width > 300px

---

.changeset/fix-DatePicker-update-focus-behaviour.md
packages/react-magma-dom/src/components/DatePicker/CalendarContext.ts
packages/react-magma-dom/src/components/DatePicker/CalendarDay.test.js
packages/react-magma-dom/src/components/DatePicker/CalendarDay.tsx
packages/react-magma-dom/src/components/DatePicker/index.tsx

Closes: #1879 
- Updated focus behavior when the user selects a day in the calendar.
Go to `Storybook` -> `Date Picker` -> `Default` -> select day in current month -> while clicking on the day, the focus **SHOULD** go to this date
Go to `Storybook` -> `Date Picker` -> `Default` -> select day in next or previous current month -> while clicking on the day, the focus **SHOULD** **NOT** go to this date

fix(Date Picker): Update selecting focus behaviour

---

.changeset/feat-drawer-isAnimated.md
packages/react-magma-dom/src/components/DatePicker/DatePicker.test.js
packages/react-magma-dom/src/components/Drawer/Drawer.stories.tsx
packages/react-magma-dom/src/components/Drawer/Drawer.test.js
packages/react-magma-dom/src/components/Drawer/Drawer.tsx
website/react-magma-docs/src/pages/api/drawer.mdx

Closes: #1890
Added isAnimated prop to control slide animation, the animation has been broken since v4.0.0 so making it disabled by default wont be a breaking change. fixing it is what caused the regression on dev
https://storybook-preview-dev--upbeat-sinoussi-f675aa.netlify.app/?path=/story/drawer--default
test isAnimated prop behaviour

feat(drawer): add isanimated prop to control slide animation

---

.changeset/fix-React-Magma-docs-before-release.md
packages/react-magma-dom/src/index.ts
website/react-magma-docs/src/pages/api/list.mdx
website/react-magma-docs/src/pages/api/loading-indicator.mdx
website/react-magma-docs/src/pages/api/native-select.mdx
website/react-magma-docs/src/pages/api/nav-tabs.mdx
website/react-magma-docs/src/pages/api/popover.mdx

Closes: #1913
Fixed bugs for React Magma Docs for these components:
- List
- Popover
- Native Select
- Nav Tabs
- Loading Indicator
**React Magma Docs**
- Go to **Components** -> **List** -> **Definition List** ->  Open CodeSandBox example -> in the example shouldn't be any errors. (DefinitionListType error)
- Go to **Components** -> **Loading Indicator** -> **Progress Bar** -> Go to CodeSandbox example -> in the example shouldn't be any errors. (LoadingIndicatorType error)
- Go to **Components** -> **Native Select** -> **Additional Content** -> Go to CodeSandbox example -> in the example shouldn't be any errors. (Property 'fieldId' is missing in type error)
- Go to **Components** -> **Nav Tabs** -> *Vertical Tabs** -> Click on `Link 2` and all other examples-> the page should not scroll …

fix(List, Nav Tabs, Popover, Native Select, Loading Indicator): Fix docs bugs before release 4.10

---

.changeset/fix-Tooltip-non-interactive-focus.md
packages/react-magma-dom/src/components/Tooltip/Tooltip.stories.tsx
website/react-magma-docs/src/pages/api/tooltip.mdx

Closes: #1922
Fix issue with screenreaders on non interactive elements
Open docs -> Tooltip -> `On non-interactive element` section -> Turn on VoiceOver/NVDA -> Check behavior 
**Note**
On Windows 10/11 + Firefox, NVDA announces it twice because of content + aria-label

fix(Tooltip): Fix issue with screenreaders on non interactive elements
