cengage/react-magma

README.md

removed mentions of archived packages and Cypress tests until those are reintroduced

docs(readme): cleaned up outdated into

---

packages/react-magma-docs/src/pages/api/badge.mdx
packages/react-magma-docs/src/pages/api/banner.mdx
packages/react-magma-docs/src/pages/api/breadcrumb.mdx
packages/react-magma-docs/src/pages/api/checkboxes.mdx
packages/react-magma-docs/src/pages/api/combobox.mdx
packages/react-magma-docs/src/pages/api/date-pickers.mdx
packages/react-magma-docs/src/pages/api/dropdown.mdx
packages/react-magma-docs/src/pages/api/formgroup.mdx
packages/react-magma-docs/src/pages/api/heading.mdx
packages/react-magma-docs/src/pages/api/hide-at-breakpoint.mdx
packages/react-magma-docs/src/pages/api/hyperlink.mdx
packages/react-magma-docs/src/pages/api/loading-indicator.mdx
packages/react-magma-docs/src/pages/api/modal.mdx
packages/react-magma-docs/src/pages/api/paragraph.mdx
packages/react-magma-docs/src/pages/api/password-input.mdx
packages/react-magma-docs/src/pages/api/progress-bar.mdx
packages/react-magma-docs/src/pages/api/radio.mdx
packages/react-magma-docs/src/pages/api/search.mdx
packages/react-magma-docs/src/pages/api/select.mdx
packages/react-magma-docs/src/pages/api/skip-link.mdx
packages/react-magma-docs/src/pages/api/spinner.mdx
packages/react-magma-docs/src/pages/api/table.mdx
packages/react-magma-docs/src/pages/api/tabs.mdx
packages/react-magma-docs/src/pages/api/textarea.mdx
packages/react-magma-docs/src/pages/api/time-picker.mdx
packages/react-magma-docs/src/pages/api/toast.mdx
packages/react-magma-docs/src/pages/api/toggle.mdx
packages/react-magma-docs/src/pages/api/tooltip.mdx
packages/react-magma-docs/src/pages/api/visually-hidden.mdx

docs(simplepropstable): remove SimplePropsTable import in docs pages

---

packages/react-magma-docs/src/pages/design-intro/introduction.mdx

Added link to Sketch libraries on Dropbox and updated language.

docs: sketch libraries link

---

.github/workflows/preview.yml

ci(actions): write comment on PRs with the preview

---

.github/workflows/add_issues_to_project.yaml

ci(actions): add issues to Triage in the react-magma project by default

---

packages/react-magma-docs/src/components/MainNav/SubMenu.js
packages/react-magma-docs/src/components/MainNav/index.js
packages/react-magma-docs/src/pages/design-intro/colors.mdx
packages/react-magma-docs/src/pages/design-intro/get-started.mdx
packages/react-magma-docs/src/pages/design-intro/typography.mdx

- Updated design intro
- Moved colors and typography to top level
- Created subgroup Components
- Styling updates for clearer hierarchy

docs: update design docs nav

---

packages/react-magma-dom/CHANGELOG.md
packages/react-magma-dom/package-lock.json
packages/react-magma-dom/package.json
packages/react-magma-icons/CHANGELOG.md
packages/react-magma-icons/package-lock.json
packages/react-magma-icons/package.json
website/react-magma-docs/CHANGELOG.md
website/react-magma-docs/package-lock.json
website/react-magma-docs/package.json
website/react-magma-landing/CHANGELOG.md
website/react-magma-landing/package-lock.json
website/react-magma-landing/package.json

- react-magma-dom@2.3.6-alpha.0
- react-magma-icons@1.0.10-alpha.0
- react-magma-docs@2.1.5-alpha.0
- react-magma-landing@1.0.5-alpha.0

chore(release): publish

---

website/react-magma-docs/src/components/layout.css
website/react-magma-docs/src/pages/api/icon.mdx

Refined the presentation of the icons on the api docs page.  Improved grid layout, responsive
behavior, and handling of long icon names.

docs: update icon presentation

---

packages/react-magma-dom/src/components/Input/Input.test.js
packages/react-magma-dom/src/components/Input/InputMessage.tsx
packages/react-magma-dom/src/components/PasswordInput/PasswordInput.test.js
packages/react-magma-dom/src/components/Textarea/Textarea.test.js

Changes to styling to accommodate inverse errors.

feat: updating styling for inverse errors

---

packages/react-magma-dom/src/components/DatePicker/DatePicker.test.js
packages/react-magma-dom/src/components/DatePicker/index.tsx

fix(date-picker): fix the calendar focus when minDate is after today

---

.changeset/frank-puppies-sleep.md
package-lock.json
package.json
packages/react-magma-dom/src/components/Toggle/Toggle.test.js
packages/react-magma-dom/src/components/Toggle/index.tsx
website/react-magma-docs/src/pages/api/toggle.mdx

fix: add controlled toggles

---

package-lock.json
website/react-magma-docs/src/pages/design-intro/layout.mdx

docs: updated layout docs

---

.changeset/selfish-crews-sing.md
package-lock.json
packages/react-magma-dom/src/components/Combobox/Combobox.tsx
packages/react-magma-dom/src/components/DatePicker/index.tsx
packages/react-magma-dom/src/components/Input/Input.stories.tsx
packages/react-magma-dom/src/components/Input/Input.test.js
packages/react-magma-dom/src/components/InputBase/InputBase.stories.tsx
packages/react-magma-dom/src/components/InputBase/index.tsx
packages/react-magma-dom/src/components/Search/Search.stories.tsx
packages/react-magma-dom/src/components/Search/index.tsx
packages/react-magma-dom/src/i18n/default.ts
packages/react-magma-dom/src/i18n/interface.ts
website/react-magma-docs/src/pages/api/input.mdx

feat(input): added isClearable prop to input base

---

.changeset/fresh-deers-reply.md
packages/react-magma-dom/src/components/Banner/index.tsx

Banner alignment changed to left justified per Orion.

refactor(text alignment): changing the banner alignment to left aligned

---

.changeset/chatty-pans-fail.md
packages/react-magma-dom/src/components/Modal/Modal.tsx

Whatever was behind the modal was scrollable so I changed how the CSS is applied.

fix(modal): stopped background from scrolling when a modal is open

---

.changeset/hot-chefs-hammer.md
website/docs/src/components/Intro/IndexPageContent.js
website/docs/src/components/LayoutComponent/index.js
website/docs/src/components/MainContainer/index.js
website/docs/src/components/SideBar/SideBar.js
website/docs/src/components/SideBar/SideBarContent.js
website/docs/src/components/SideBar/index.js

Adding up the sidebar with dummy links in the meantime!

V3 Feature/new sidebar

---

.changeset/polite-bags-divide.md
package-lock.json
packages/react-magma-dom/src/components/InputBase/index.tsx
packages/react-magma-dom/src/components/Search/Search.stories.tsx
packages/react-magma-dom/src/components/Search/index.tsx
website/react-magma-docs/src/pages/api/search.mdx

Adding in new prop within InputBase to allow for the Predictive Search feature.

feat: Predictive Search

---

.changeset/few-wasps-cry.md
packages/react-magma-dom/src/components/FormFieldContainer/FormFieldContainer.tsx
packages/react-magma-dom/src/components/Input/InputMessage.tsx
packages/react-magma-dom/src/components/Select/SelectContainer.tsx

Removed bottom margin per ticket on Form Field Container.

feat: Inputs update

---

.changeset/itchy-stingrays-build.md
patterns/header/src/components/header/Header.stories.tsx

docs(header): fix isInverse example in patterns header

---

.changeset/cool-llamas-taste.md
packages/react-magma-dom/src/components/Modal/Modal.tsx

fix https://github.com/cengage/react-magma/issues/614

fix(modal.tsx): Remove title attribute from modals

---

.changeset/stupid-cougars-divide.md
packages/schema-renderer/src/components/SchemaRenderer/SchemaRenderer.stories.tsx

aligned schema data in the stories to be similar to the documentation
fix #574 
fix #572

fix(schemarenderer.stories.tsx): clean up schema data

---

.changeset/clean-owls-help.md
packages/react-magma-dom/src/components/Alert/__snapshots__/Alert.test.js.snap
packages/react-magma-dom/src/components/AlertBase/index.tsx

fix(alert): add right padding of 12px

---

.changeset/warm-windows-care.md
packages/react-magma-dom/src/components/Input/Input.test.js
packages/react-magma-dom/src/components/InputBase/index.tsx
packages/react-magma-dom/src/components/PasswordInput/PasswordInput.test.js

fix(InputBase/index.tsx): fix alignment for "Choose file" button for inputSize large

---

.changeset/icon-button-misc.md
packages/react-magma-dom/src/components/IconButton/IconButton.stories.tsx

fix(iconbutton.stories.tsx): Removing some controls from Icon Only and Animated Icon stories

---

.changeset/select-multi-fix.md
packages/react-magma-dom/src/components/Select/Select.stories.tsx

fix(select.stories.tsx): fixing Select Multi story

---

.changeset/new-owls-perform.md
packages/dropzone/src/components/dropzone/Dropzone.stories.tsx

Fix https://github.com/cengage/react-magma/issues/570 & https://github.com/cengage/react-magma/issues/571
1. Updating the Dropzone preview for Image/Text/CSV when controls are toggled
2. Removing the image or file preview after they have been deleted
_lots of spacing changes because I ran prettier on the file_

fix(dropzone.stories.tsx): Preview updates correctly & deleted file is removed

---

.changeset/dry-clouds-mix.md
packages/react-magma-dom/src/components/Accordion/Accordion.stories.tsx
packages/react-magma-dom/src/components/Accordion/Accordion.test.js
packages/react-magma-dom/src/components/Accordion/Accordion.tsx
packages/react-magma-dom/src/components/Accordion/AccordionButton.tsx
packages/react-magma-dom/src/components/Accordion/AccordionPanel.tsx

1. fix #532 & #533
2. Change accordion background color to transparent (so it works better for the inverse)

fix(accordion.stories.tsx): fix Accordion expand collapse all story & change background to transparent

---

.changeset/rebrand-cards.md
packages/react-magma-dom/src/components/Alert/__snapshots__/Alert.test.js.snap
packages/react-magma-dom/src/components/Button/__snapshots__/Button.test.js.snap
packages/react-magma-dom/src/components/Card/Card.stories.tsx
packages/react-magma-dom/src/components/Card/Card.test.js
packages/react-magma-dom/src/components/Card/Card.tsx
packages/react-magma-dom/src/components/IconButton/__snapshots__/IconButton.test.js.snap
packages/react-magma-dom/src/components/SkipLink/__snapshots__/SkipLink.test.js.snap
packages/react-magma-dom/src/components/Tooltip/__snapshots__/Tooltip.test.js.snap
packages/react-magma-dom/src/theme/magma.ts
website/react-magma-docs/src/pages/api/card.mdx

feat(cards): updating cards with rebrand colors

---

.changeset/rebrand-breadcrumbs.md
packages/react-magma-dom/src/components/Breadcrumb/Breadcrumb.stories.tsx
packages/react-magma-dom/src/components/Breadcrumb/BreadcrumbItem.tsx
packages/react-magma-dom/src/components/Hyperlink/Hyperlink.test.js
packages/react-magma-dom/src/components/Hyperlink/index.tsx

feat(breadcrumb): updating breadcrumb colors

---

.changeset/rebrand-badge.md
packages/react-magma-dom/src/components/Badge/Badge.stories.tsx
packages/react-magma-dom/src/components/Badge/Badge.test.js
packages/react-magma-dom/src/components/Badge/index.tsx

feat(badge): updating badge colors. Adding `isInverse` support

---

.changeset/rebrand-accordion.md
packages/react-magma-dom/src/components/Accordion/AccordionButton.tsx
packages/react-magma-dom/src/components/Accordion/AccordionPanel.tsx

feat(accordion): updating accordion with new colors

---

.changeset/bug-textarea.md
packages/react-magma-dom/src/components/Textarea/Textarea.stories.tsx
packages/react-magma-dom/src/components/Textarea/Textarea.test.js
packages/react-magma-dom/src/components/Textarea/index.tsx

fix https://github.com/cengage/react-magma/issues/676
Note: this pull request will go to main so we can patch the currently released version

fix(textarea): textarea has ability to be cleared

---

.changeset/rare-eagles-drop.md
website/react-magma-docs/src/pages/patterns/header.mdx

Adding in step for Setup Requirements for clarification, caught by Tom Nagy.

docs: updating header setup requirements

---

.changeset/rebrand-tabs.md
packages/react-magma-dom/src/components/NavTabs/NavTabs.stories.tsx
packages/react-magma-dom/src/components/NavTabs/NavTabs.tsx
packages/react-magma-dom/src/components/Tabs/Tab.test.js
packages/react-magma-dom/src/components/Tabs/Tab.tsx
packages/react-magma-dom/src/components/Tabs/TabPanel.test.js
packages/react-magma-dom/src/components/Tabs/TabPanel.tsx
packages/react-magma-dom/src/components/Tabs/TabPanelsContainer.test.js
packages/react-magma-dom/src/components/Tabs/Tabs.stories.tsx
packages/react-magma-dom/src/components/Tabs/Tabs.test.js
packages/react-magma-dom/src/components/Tabs/Tabs.tsx
packages/react-magma-dom/src/components/Tabs/TabsContainer.test.js
packages/react-magma-dom/src/components/Tabs/TabsContainer.tsx
packages/react-magma-dom/src/components/Tabs/TabsScrollButtons.tsx
packages/react-magma-dom/src/components/Tabs/utils.ts

feat(tab/navtabs): updating tabs and nav tabs with new colors

---

.changeset/rebrand-dropzone.md
packages/dropzone/package-lock.json
packages/dropzone/package.json
packages/dropzone/src/components/dropzone/Dropzone.stories.tsx
packages/dropzone/src/components/dropzone/Dropzone.test.js
packages/dropzone/src/components/dropzone/Dropzone.tsx
packages/dropzone/src/components/dropzone/FileIcon.tsx
packages/dropzone/src/components/dropzone/Preview.tsx

feat(dropzone): updating dropzone colors

---

.changeset/rebrand-expressive-docs.md
.changeset/rebrand-expressive.md
packages/react-magma-dom/src/components/Heading/Heading.stories.tsx
packages/react-magma-dom/src/components/Heading/index.tsx
packages/react-magma-dom/src/components/Paragraph/Paragraph.stories.tsx
packages/react-magma-dom/src/components/Typography/index.tsx
packages/react-magma-dom/src/theme/magma.ts
website/react-magma-docs/src/components/Intro/IndexPageContent.js
website/react-magma-docs/src/pages/api/theme.mdx
website/react-magma-docs/src/pages/design-intro/typography.mdx
website/react-magma-landing/templates/index.html

feat(heading): update heading expressive `contextVariant` styles

---

.changeset/select-hover-bug.md
packages/react-magma-dom/src/components/Select/shared.ts

fix(select): fix hover styles in Select component to not have focus border

---

.changeset/combobox-multi-styles.md
packages/react-magma-dom/src/components/Combobox/Combobox.stories.tsx
packages/react-magma-dom/src/components/Combobox/ComboboxInput.tsx
packages/react-magma-dom/src/components/Combobox/MultiCombobox.tsx
packages/react-magma-dom/src/components/Input/Input.test.js
packages/react-magma-dom/src/components/InputBase/index.tsx
packages/react-magma-dom/src/components/Select/MultiSelect.tsx
packages/react-magma-dom/src/components/Select/Select.stories.tsx
packages/react-magma-dom/src/components/Select/shared.ts

fix(combobox): update combobox items colors and error styling

---

.changeset/docs-breakpoints.md
packages/react-magma-dom/src/components/BreakpointsContainer/BreakpointsContainer.stories.tsx
website/react-magma-docs/src/pages/api/breakpoints-container.mdx

docs(breakpointscontainer): update breakpoints container examples

---

.changeset/combobox-spinner-inverse.md
packages/react-magma-dom/src/components/Combobox/Combobox.stories.tsx
packages/react-magma-dom/src/components/Combobox/Combobox.tsx
packages/react-magma-dom/src/components/Combobox/MultiCombobox.tsx
packages/react-magma-dom/src/components/Search/index.tsx
packages/react-magma-dom/src/components/Select/ItemsList.tsx
packages/react-magma-dom/src/components/Select/MultiSelect.tsx
packages/react-magma-dom/src/components/Select/Select.tsx
packages/react-magma-dom/src/components/Select/components.tsx
packages/react-magma-dom/src/components/Select/shared.ts
packages/react-magma-dom/src/components/Spinner/Spinner.stories.tsx
packages/react-magma-dom/src/components/Spinner/index.tsx
website/react-magma-docs/src/pages/api/spinner.mdx

re #731
_Also,_ 
feat(spinner): Add `isInverse` support for Spinner component.

feat(combobox/select): update styling for items list inverse

---

.changeset/wild-frogs-eat.md
website/react-magma-docs/src/pages/api/theme.mdx

docs: theming update for v3

---

.changeset/rebrand-datepicker.md
packages/react-magma-dom/src/components/DatePicker/CalendarContext.ts
packages/react-magma-dom/src/components/DatePicker/CalendarDay.tsx
packages/react-magma-dom/src/components/DatePicker/CalendarHeader.tsx
packages/react-magma-dom/src/components/DatePicker/CalendarMonth.tsx
packages/react-magma-dom/src/components/DatePicker/DatePicker.stories.tsx
packages/react-magma-dom/src/components/DatePicker/HelperInformation.tsx
packages/react-magma-dom/src/components/DatePicker/index.tsx
website/react-magma-docs/src/pages/api/date-pickers.mdx

re https://github.com/cengage/react-magma/issues/715 & https://github.com/cengage/react-magma/issues/716

feat(datepicker): update DatePicker with new colors

---

.changeset/violet-jars-rest.md
packages/react-magma-dom/src/components/AlertBase/index.tsx
packages/react-magma-dom/src/components/Toast/Toast.stories.tsx
website/react-magma-docs/src/pages/api/toast.mdx

Fixing alignment for circle animation when text breaks to a second line.

fix: Toast X center alignment

---

.changeset/sortable-tables.md
packages/react-magma-dom/src/components/Table/TableHeaderCell.tsx
website/react-magma-docs/src/pages/api/table.mdx

fix(table): update sortable table header cursor

---

.changeset/colors-badge-docs.md
website/react-magma-docs/src/components/ColorSwatch/index.js

fix #751
**before:**
**after:**

fix: update badges in colors tiles

---

.changeset/patch-alerts-fix.md
packages/react-magma-dom/src/components/Alert/Alert.stories.tsx
packages/react-magma-dom/src/components/Alert/__snapshots__/Alert.test.js.snap
packages/react-magma-dom/src/components/AlertBase/index.tsx

Regarding: [754](https://github.com/cengage/react-magma/issues/754)

fix: Close button alignment on Alerts

---

.changeset/container-storybook.md
packages/react-magma-dom/src/components/Container/Container.stories.tsx

fix(container): update Storybook examples

---

.changeset/badge-colors.md
packages/react-magma-dom/src/components/Badge/Badge.test.js
packages/react-magma-dom/src/components/Badge/index.tsx

fix(badge): update hover/active/focus styles

---

.changeset/tabs-storybook.md
packages/react-magma-dom/src/components/Tabs/Tabs.stories.tsx

fix(tabs): update Storybook examples

---

.changeset/timepicker-onchange.md
packages/react-magma-dom/src/components/TimePicker/TimePicker.test.js
packages/react-magma-dom/src/components/TimePicker/TimePicker.tsx
packages/react-magma-dom/src/components/TimePicker/useTimePicker.ts
website/react-magma-docs/src/pages/api/time-picker.mdx

fix #314
Added unit tests and example in docs for easy testing.

fix(timepicker): `onChange` is called on 'Backspace' key press

---

.changeset/modal-isInverse.md
packages/react-magma-dom/src/components/Modal/Modal.stories.tsx
website/react-magma-docs/src/pages/api/modal.mdx

Also update `isInverse` example in storybook
fix #802

docs(modal): add `isInverse` example

---

.changeset/buttongroup-dropdown.md
.changeset/remove-deprecation.md
packages/react-magma-dom/src/components/Dropdown/Dropdown.test.js
packages/react-magma-dom/src/components/Dropdown/Dropdown.tsx
website/react-magma-docs/src/pages/api/dropdown.mdx

dropdown: remove deprecated prop `onBeforeShiftFocus`

---

.changeset/buttongroup-dropdown.md
packages/react-magma-dom/src/components/ButtonGroup/ButtonGroup.stories.tsx
packages/react-magma-dom/src/components/ButtonGroup/ButtonGroup.test.js
packages/react-magma-dom/src/components/ButtonGroup/__snapshots__/ButtonGroup.test.js.snap
packages/react-magma-dom/src/components/ButtonGroup/index.tsx
packages/react-magma-dom/src/components/Dropdown/Dropdown.stories.tsx
packages/react-magma-dom/src/components/Dropdown/Dropdown.tsx
packages/react-magma-dom/src/components/Dropdown/DropdownSplitButton.tsx
website/react-magma-docs/src/pages/api/button-group.mdx
website/react-magma-docs/src/pages/api/button.mdx
website/react-magma-docs/src/pages/api/dropdown.mdx

feat(buttongroup): add `Dropdown` support

---

.changeset/datagrid-docs.md
website/react-magma-docs/src/pages/api/datagrid.mdx

docs(datagrid): update Datagrid `Row Colors` example

---

.changeset/pre.json
.changeset/release-dom.md
packages/react-magma-dom/CHANGELOG.md

The last PR did not release the 3.0.0 prerelease versions, so bumping the version here to get the actual 3.1.0 release

Bump react-magma-dom version

---

.changeset/bug-native-select.md
packages/react-magma-dom/src/components/NativeSelect/NativeSelect.test.js
packages/react-magma-dom/src/components/NativeSelect/NativeSelect.tsx
packages/react-magma-dom/src/components/Select/Select.stories.tsx

Reworking component by removing SelectTriggerButton which should fix: [830](https://github.com/cengage/react-magma/issues/830) & [330](https://github.com/cengage/react-magma/issues/330).

fix: Native Select - dropdown menu

---

.changeset/datepicker-format-support.md
packages/react-magma-dom/src/components/DatePicker/DatePicker.stories.tsx
packages/react-magma-dom/src/components/DatePicker/DatePicker.test.js
packages/react-magma-dom/src/components/DatePicker/index.tsx
packages/react-magma-dom/src/i18n/interface.ts
website/react-magma-docs/src/pages/api/date-pickers.mdx

fix(datepicker): fix support for non-default date formats (dd/mm/yyyy, yyyy/MM/dd, yyyy/dd/MM)

---

.changeset/appbar-a11y.md
packages/react-magma-dom/src/components/AppBar/AppBar.stories.tsx
website/react-magma-docs/src/pages/api/appbar.mdx

refactor(appbar): update Storybook example with a11y violations

---

.changeset/radio-storybooka11y.md
packages/react-magma-dom/src/components/Radio/Radio.stories.tsx

fix #514
**😢 Before:**
**😀 After:**

refactor(radio): update Storybook examples with a11y violations

---

.changeset/skiplink-a11y.md
packages/react-magma-dom/src/components/SkipLink/SkipLink.stories.tsx

refactor(skiplink): update Storybook example with a11y violations

---

.changeset/accordion_a11y.md
packages/react-magma-dom/src/components/Accordion/AccordionPanel.tsx
packages/react-magma-dom/src/components/Accordion/useAccordionItem.ts
packages/react-magma-dom/src/utils/index.ts

refactor(accordion): Update Storybook example with a11y violations.
fix #488 #489 #490 
---
**Accessibility issues this addresses:**

fix(accordion): Accordion Item `buttonId` will be based on the index to avoid duplicate ids.

---

.changeset/indeterminate-a11y.md
packages/react-magma-dom/src/components/IndeterminateCheckbox/IndeterminateCheckbox.stories.tsx

refactor(indeterminatecheckbox): update Storybook example with a11y violations

---

.changeset/double-focus.md
packages/react-magma-dom/src/components/DatePicker/DatePicker.stories.tsx
packages/react-magma-dom/src/components/FormFieldContainer/FormFieldContainer.tsx
packages/react-magma-dom/src/components/InputBase/index.tsx
packages/react-magma-dom/src/components/PasswordInput/PasswordInput.stories.tsx
packages/react-magma-dom/src/components/PasswordInput/index.tsx
packages/react-magma-dom/src/components/Search/Search.stories.tsx
packages/react-magma-dom/src/components/Search/index.tsx

fix #799
---
**Before:**
---
**After:**

fix(input): fix double focus on all input types (search, datepicker, password)

---

.changeset/docs-props-table.md
packages/react-magma-dom/src/components/Accordion/Accordion.tsx
website/react-magma-docs/src/components/SimplePropsTable/index.js
website/react-magma-docs/src/pages/api/accordion.mdx
website/react-magma-docs/src/pages/api/dropdown.mdx

#317
We don't currently have any deprecated props, so here's an example of how that would look:

docs(simplepropstable): updating layout of props tables

---

.changeset/input_isClearable.md
packages/react-magma-dom/src/components/Input/Input.stories.tsx
packages/react-magma-dom/src/components/InputBase/index.tsx

Issue: #889 
Bug Fix: Fix the double focus that occurs on inputs when there is an `isClearable` button. This affects `Input`
Check the following stories:
[Input without Icon](https://storybook-preview-892--upbeat-sinoussi-f675aa.netlify.app/?path=/story/input--default&args=isClearable:true)
-- check with `isClearable` flag on and off
[Input with Icon](https://storybook-preview-892--upbeat-sinoussi-f675aa.netlify.app/?path=/story/input--icon-top): 
-- check with `isClearable` flag on and off (ensure that if text fills the input, the text doesn't get covered by the icons)
-- change the `iconPosition` 
-- change the `inputSize`
[Input with …

fix(input): fix double focus on the `isClearable` button on all input types

---

.github/workflows/add_issues_to_project.yaml

Issue: _none_
Our Github workflow keeps failing since we deleted the old project:
This is to update that workflow with our new project URL.

(chore): Fix add_issues_to_project workflow

---

.changeset/a11y-docs.md
website/react-magma-docs/src/pages/api/card.mdx
website/react-magma-docs/src/pages/api/combobox.mdx
website/react-magma-docs/src/pages/api/icon-button.mdx
website/react-magma-docs/src/pages/api/radio.mdx
website/react-magma-docs/src/pages/api/search.mdx
website/react-magma-docs/src/pages/api/select.mdx

Issue: #273
Updated docs examples with a11y issues:
- Updated the following pages to remove duplicate IDs
-- Combobox
-- Radio buttons
-- Select
-- Nav Tabs
-- Search
- Added alt attribute to Card example
- Fixed aria-labels for Icon Buttons
- [N/A] New and existing unit tests pass locally with my changes
- Review docs for the pages mentioned above

docs: various a11y fixes including duplicate IDs, missing alt attributes, missing aria-labels

---

.changeset/fix-characterCounter.md
packages/react-magma-dom/src/components/CharacterCounter/CharacterCounter.test.js
packages/react-magma-dom/src/components/CharacterCounter/CharacterCounter.tsx
packages/react-magma-dom/src/components/FormFieldContainer/FormFieldContainer.tsx
packages/react-magma-dom/src/components/Input/InputMessage.tsx
packages/react-magma-dom/src/components/Input/index.tsx

Issue: # [941](https://github.com/cengage/react-magma/issues/941)
Added dynamic aria-live states based on feedback from Perkins.
Ensure that aria-live label is "off" until you reach 80% of text within the input, "live" after 80% is reached, and "assertive" when you're over 100%.

Character Counter: a11y improvements

---

.changeset/fix-build.md
package-lock.json
packages/react-magma-dom/scripts/copy-changelog.js

Fixing last build that failed with the following error:

chore: Fix build

---

packages/react-magma-dom/src/components/Input/Input.stories.tsx
packages/react-magma-dom/src/components/InputBase/index.tsx
packages/react-magma-dom/src/components/ToggleButton/ToggleButton.stories.tsx
packages/react-magma-dom/src/components/ToggleButton/ToggleButton.test.js
packages/react-magma-dom/src/components/ToggleButton/ToggleButton.tsx
packages/react-magma-dom/src/components/ToggleButtonGroup/ToggleButtonGroup.stories.tsx
packages/react-magma-dom/src/components/ToggleButtonGroup/ToggleButtonGroup.test.js
packages/react-magma-dom/src/components/ToggleButtonGroup/ToggleButtonGroup.tsx

Refactoring and updating Toggle Button. TO be merged to the original feat/toggleButton branch

Toggle Button v2

---

.changeset/fix-inputwrapper.md
packages/react-magma-dom/src/components/InputBase/index.tsx
packages/react-magma-dom/src/components/PasswordInput/index.tsx

Issue: #
Added width prop to InputBase so that width is passed through to the input element.

fix(inputbase): update width prop

---

.changeset/heading-css.md
packages/react-magma-dom/src/components/Heading/index.tsx

Issue: #410
Added CSS as an internal & optional prop to Heading component. I see that this has been done for LoadingIndicator, NavTabs and Radio, as this seems to be an emotion issue.
Unfortunately, I'm not sure how to test it other than push and test if it fixes the issue when used in another app.

fix(heading): Fix error that `"Property 'css' is missing"`

---

.changeset/character-counter-value.md
packages/react-magma-dom/src/components/CharacterCounter/CharacterCounter.stories.tsx
packages/react-magma-dom/src/components/Input/Input.test.js
packages/react-magma-dom/src/components/Input/index.tsx
packages/react-magma-dom/src/components/Search/index.tsx
packages/react-magma-dom/src/components/Textarea/Textarea.stories.tsx
packages/react-magma-dom/src/components/Textarea/Textarea.test.js
packages/react-magma-dom/src/components/Textarea/index.tsx
website/react-magma-docs/src/pages/api/character-counter.mdx

Issue: [1001](https://github.com/cengage/react-magma/issues/1001)
- Added value prop capability to Inputs and Textareas using Character Counter for a fix.
Verify that any given Input or Textarea using maxLength="" properly subtracts the value="" text on initial page load.

Fix/character counter - value

---

.github/workflows/add_issues_to_project.yaml

Fixing the workflow fun failure:

chore: Update Add Issues to Project workflow

---

.changeset/grid-docs.md
packages/react-magma-dom/src/components/Grid/Grid.stories.tsx
packages/react-magma-dom/src/components/Grid/Grid.tsx
website/react-magma-docs/src/pages/api/grid.mdx

Issue: none
Explain `as` prop that has caused some confusion, and update docs.
Review the Grid docs page and ensure it makes more sense.

docs(grid): Update Grid documentation and explain `as` prop

---

.changeset/gold-pears-travel.md
.changeset/input-focus-stack.md
.changeset/pre.json
packages/react-magma-dom/CHANGELOG.md
packages/react-magma-dom/package.json
packages/react-magma-dom/src/components/InputBase/index.tsx
website/react-magma-docs/CHANGELOG.md
website/react-magma-docs/package.json

Reverting https://github.com/cengage/react-magma/pull/1089 for now, and will revisit after the release

chore: Revert Input outline commits

---

.github/workflows/preview.yml
.github/workflows/publish-latest.yml
.github/workflows/publish-next-patch.yml
.github/workflows/publish-patch.yml

chore: Update GitHub workflows

---

.changeset/docs-typos.md
website/react-magma-docs/src/pages/design/alert.mdx
website/react-magma-docs/src/pages/design/checkboxes.mdx
website/react-magma-docs/src/pages/design/combobox.mdx
website/react-magma-docs/src/pages/design/indeterminate.mdx
website/react-magma-docs/src/pages/design/input.mdx
website/react-magma-docs/src/pages/design/password-input.mdx
website/react-magma-docs/src/pages/design/tag.mdx
website/react-magma-docs/src/pages/design/toast.mdx
website/react-magma-docs/src/pages/design/toggle.mdx

docs: Fix typos

---

.changeset/sortArrows.md
packages/react-magma-dom/src/components/Table/TableHeaderCell.tsx
packages/react-magma-dom/src/components/Table/TableRow.tsx

Issue: #1121
Update arrows
Test:
- Sortable table
- Sortable datagrid

fix(table/datagrid): Update ascending and descending arrows

---

.changeset/dropdown-menuItemRole.md
packages/react-magma-dom/src/components/Dropdown/DropdownExpandableMenuItem.tsx
packages/react-magma-dom/src/components/Dropdown/DropdownExpandableMenuListItem.tsx

Add `role="menuitem"` to `DropdownExpandableMenuListItem` to match `DropdownMenuItem`
Confirm in the DOM that the role is attached to the right element. Confirm in storybook there are no a11y violations.

fix(DropdownExpandableMenuListItem): Add role

---

.changeset/timepicker-add-clearable-option.md
packages/react-magma-dom/src/components/TimePicker/TimePicker.stories.tsx
packages/react-magma-dom/src/components/TimePicker/TimePicker.test.js
packages/react-magma-dom/src/components/TimePicker/useTimePicker.ts
website/react-magma-docs/src/pages/api/time-picker.mdx

Issue: [#1230](https://github.com/cengage/react-magma/issues/1230)
New feature (Added opportunity to clear Timepicker).
1. Run storybook;
2. Open the TimePicker and new example "Clearable";
3. Add time and click on button "Clear Time".

feat (TimePicker): Added opportunity to clear value

---

.changeset/treeview-refactor.md
packages/react-magma-dom/src/components/TreeView/TreeView.stories.tsx
packages/react-magma-dom/src/components/TreeView/TreeView.test.js
packages/react-magma-dom/src/components/TreeView/TreeViewContext.ts
packages/react-magma-dom/src/components/TreeView/useTreeItem.ts
packages/react-magma-dom/src/components/TreeView/useTreeView.ts
website/react-magma-docs/src/pages/api/tree-view.mdx

feat(TreeView): Refactor prop names

---

.changeset/treeview-nav.md
.storybook/main.js
packages/react-magma-dom/src/components/Checkbox/index.tsx
packages/react-magma-dom/src/components/IndeterminateCheckbox/index.tsx
packages/react-magma-dom/src/components/TreeView/TreeItem.tsx
packages/react-magma-dom/src/components/TreeView/TreeView.stories.tsx
packages/react-magma-dom/src/components/TreeView/TreeView.test.js
packages/react-magma-dom/src/components/TreeView/TreeView.tsx
packages/react-magma-dom/src/components/TreeView/TreeViewContext.ts
packages/react-magma-dom/src/components/TreeView/useTreeItem.ts
packages/react-magma-dom/src/components/TreeView/useTreeView.ts
packages/react-magma-dom/src/components/TreeView/utils.ts

Issue: #
Update Keyboard Navigation and Focus

TreeView: Update Keyboard Navigation and Focus

---

.changeset/fix-events.md
packages/react-magma-dom/src/components/Combobox/Combobox.tsx
packages/react-magma-dom/src/components/Combobox/ComboboxInput.tsx
packages/react-magma-dom/src/components/Combobox/MultiCombobox.tsx
packages/react-magma-dom/src/components/Select/MultiSelect.tsx
packages/react-magma-dom/src/components/Select/Select.tsx

Issue: none
Typescript is unhappy with our mismatching types. Changing it to avoid this being an issue when building the project.
No visual changes.

fix(Select/Combobox): Update event types

---

.changeset/toast-docs.md
website/react-magma-docs/src/pages/api/toast.mdx

Issue: none
Add a warning to explain Toast usage.

docs(Toast): Update usage explanation

---

.changeset/docs-styles.md
packages/react-magma-dom/src/components/Alert/__snapshots__/Alert.test.js.snap
packages/react-magma-dom/src/components/AlertBase/index.tsx
website/react-magma-docs/src/pages/api-intro/styles-and-themes.mdx
website/react-magma-docs/src/pages/api-intro/usage.mdx
website/react-magma-docs/src/pages/api/combobox.mdx
website/react-magma-docs/src/pages/api/select.mdx
website/react-magma-docs/src/pages/api/transition.mdx

Issue: -
Fix various parts of the documentation site that had the type error below:
This addresses the following pages:
- API Intro > Styles and Themes > [Customization](https://docs-preview-1313--upbeat-sinoussi-f675aa.netlify.app/api-intro/styles-and-themes/#customization)
- API Intro > Usage > [Using the Magma Theme](https://docs-preview-1313--upbeat-sinoussi-f675aa.netlify.app/api-intro/usage/#using_the_magma_theme)
- API > Combobox > [Custom Item Component](https://docs-preview-1313--upbeat-sinoussi-f675aa.netlify.app/api/combobox/#custom_components)
- API > Select > [Custom Item Component](https://docs-preview-1313--upbeat-sinoussi-f675aa.netlify.app/api/select/#custom_item_component)
- API > Transition > [All examples](https://docs-preview-1313--upbeat-sinoussi-f675aa.netlify.app/ap …

docs: Fix styles TypeError

---

.changeset/linechart-deprecate.md
packages/charts/src/components/LineChart/LineChart.tsx
website/react-magma-docs/src/pages/api/line-chart.mdx

Issue: #1323
Deprecate LineChart

chore: Deprecate LineChart

---

.changeset/drawer-storybook.md
packages/react-magma-dom/src/components/Drawer/Drawer.stories.tsx

Issue: #1315 follow up
Update Site Navigation storybook example to have ariaLabel
-  [-] I have added tests that prove my fix is effective or that my feature works
Confirm all Drawer storybook and docs examples have appropriate aria labels

fix(Drawer): Update site navigation storybook example

---

.changeset/datePicker-calendar-table-role.md
packages/react-magma-dom/src/components/DatePicker/CalendarMonth.tsx

Issue: #1340
**What I did**
- Bug fix: removed the role="presentation" from the date picker calendar <table> element 
**Checklist**

fix(datePicker): Fix date picker calendar table role issue (#1340)

---

.changeset/select-multiselect-console-errors.md
packages/react-magma-dom/src/components/Select/MultiSelect.tsx
packages/react-magma-dom/src/components/Select/Select.tsx

Issue: # 1361
Fix select/multiselect console errors
1.Open `Modal In A Modal ` storybook
2.Open nested modal
3.Navigate between selects using the keyboard
4.Console should be clear

fix(Select/Multiselect): Fix console errors

---

.changeset/docs-drawerExample.md
website/react-magma-docs/src/pages/api/drawer.mdx

Issue: none
https://go.screenpal.com/watch/cZjrDsV9JdE
Add missing import to docs example
Test that code sandbox opens without an error on all Drawer examples

fix(Drawer): Fix Drawer Navigation example

---

.changeset/docs-drawerExample.md
.changeset/docs-drawerExample2.md
packages/react-magma-dom/src/components/Drawer/Drawer.stories.tsx
website/react-magma-docs/src/pages/api/drawer.mdx

Issue: none
Update Drawer docs examples
1. missing imports
2. example on how to update the aria label for the close button
3. styling for Drawer props so it appears on the site navigation
4. i18n example wasn't valuable
Test the drawer docs site, clicking on all the code sandbox links and ensuring it makes sense.

docs(Drawer): Fix Drawer examples

---

.changeset/a11y-iconToggleBtn.md
packages/react-magma-dom/src/components/ToggleButton/ToggleButton.stories.tsx
website/react-magma-docs/src/pages/api/toggle-button.mdx

Issue: #1235 
- Updated docs examples to include required aria-label prop for icon only (the logic to support aria label was already present)
- Confirm that all examples in docs and storybook are properly announced by screenreader
- Confirm that all icon only examples have an aria label

fix(ToggleButton): Improved accessibility for Toggle Button icon only examples

---

.changeset/datePicker-onChange.md
packages/react-magma-dom/src/components/DatePicker/DatePicker.stories.tsx
packages/react-magma-dom/src/components/DatePicker/index.tsx

Issue: #1410 
Added conditional to onChange call. Updated storybook to be able to test which also updates the unit tests.
N/A
Confirm that DatePicker with both functions can clear the date without error

fix(DatePicker): Fix error when using both onChange and onDateChange

---

.changeset/chore-emotion-dep.md
packages/react-magma-dom/package-lock.json
packages/react-magma-dom/package.json

Issue: #1411 
Moved @emotion from dependency to peerDependency in react-magma-dom
Once merged, we can try upgrading the version of an app that uses Magma to see if there are any errors.

chore: Update @emotion dependency

---

.changeset/treeViewProps.md
.changeset/treeview-docs.md
packages/react-magma-dom/src/components/TreeView/TreeView.stories.tsx
website/react-magma-docs/src/pages/api/tree-view.mdx

Issue: none
Adding a description for `checkChildren` and `checkParents` prop to the docs site, and updating the example in storybook to confirm that the expected items are selected.
Ensure that the docs site has the appropriate amount of information for adopters to understand these new props.

docs(TreeView): Update TreeView example

---

.changeset/chore-emotion-dep.md
.changeset/gentle-carpets-agree.md
packages/react-magma-dom/package-lock.json
packages/react-magma-dom/package.json

This reverts commit 3b3a2d79a804d9f3ccb125222ae91df281aadadd.

Revert "chore: Update @emotion dependency (#1419)"

---

.changeset/list.md
packages/react-magma-dom/src/components/List/List.stories.tsx
packages/react-magma-dom/src/components/List/List.tsx
packages/react-magma-dom/src/components/List/ListItem.tsx
website/react-magma-docs/src/pages/api/list.mdx

Issue: #1073
We originally thought our List component didn't support nested children. However, it does, we just needed examples of it. This is adding examples to docs and storybook.
Confirm that the List component can have nested children, and that all the examples in the docs are functional and make sense.

fix(List): Updated examples for List component

---

.changeset/fix-treeView-checked.md
packages/react-magma-dom/src/components/TreeView/TreeView.stories.tsx
packages/react-magma-dom/src/components/TreeView/useTreeItem.ts
website/react-magma-docs/src/pages/api/tree-view.mdx

Issue: #1369
- add `&& checkParents`
- fix Preselected Items

fix(treeview): Fix preselected checked

---

.changeset/a11y-search-loading.md
.changeset/search-loading.md
packages/react-magma-dom/src/components/Search/index.tsx

Issue: #1233
Changes were made to ensure that focus is maintained during loading by replacing the search icon with a spinner component. A condition was also added to prevent the button from being clickable while loading

fix(search): Fix losing focus during loading

---

.changeset/a11y-select-accessibility.md
packages/react-magma-dom/src/components/Select/MultiSelect.tsx
packages/react-magma-dom/src/components/Select/Select.tsx
packages/react-magma-dom/src/components/Select/SelectContainer.tsx
packages/react-magma-dom/src/components/Select/SelectTriggerButton.tsx
packages/react-magma-dom/src/components/Select/shared.ts
packages/react-magma-dom/src/i18n/default.ts
packages/react-magma-dom/src/i18n/interface.ts

Issue: #1390
Remove the `ClearIndicator` component outside from the `SelectTriggerButton`.

fix(Select): Fix accessibility issue. 

---

.changeset/a11y-treeview-navigation.md
packages/react-magma-dom/src/components/TreeView/TreeItem.tsx
packages/react-magma-dom/src/components/TreeView/TreeView.test.js
packages/react-magma-dom/src/components/TreeView/useTreeItem.ts

Issue: #1420
Fixed switching to Focus Mode inside `TreeView`
Enable screenreader -> Go to the storybook -> TreeView -> open any example -> use arrow up and arrow down to navigate inside TreeView

fix(treeview): fix switching to Focus Mode inside `TreeView`

---

.changeset/tree-initEx-docs.md
website/react-magma-docs/src/pages/api/tree-view.mdx

Issue: none
initialExpandedItems example was using the wrong ID so the items were not expanding as expected.
Confirm all examples in tree view docs behave as expected

docs(TreeView): Update examples

---

.changeset/a11y-dropdown-active-item.md
packages/react-magma-dom/src/components/Dropdown/DropdownMenuItem.tsx

Issue: #1439
The `menuitem` role does not support `aria-selected`, so as an alternative, `aria-checked` was added to facilitate programmatic communication of the active item and to improve accessibility.

fix(dropdown): Fix active index communication handled programmatically

---

.changeset/a11y-docs-Modal.md
website/react-magma-docs/src/pages/api/modal.mdx

Issue: #1462
fix nested modal example in docs
-
-got to /api/modal/#nested_modals
- test focus trap in both modals

fix docs nested modal example

---

.changeset/fix-blockQuote-border-color.md
.changeset/fix-listItem-icons-color.md
packages/react-magma-dom/src/components/BlockQuote/BlockQuote.stories.tsx
packages/react-magma-dom/src/components/BlockQuote/BlockQuote.test.js
packages/react-magma-dom/src/components/BlockQuote/BlockQuote.tsx
packages/react-magma-dom/src/components/List/List.test.js
packages/react-magma-dom/src/components/List/ListItem.tsx

Issue: #1126
Fix colors respecting the `Theme` context

fix(ListItem, BlockQuote): fix colors respecting the `Theme` context

---

.changeset/search-clear-overlaps.md
packages/react-magma-dom/src/components/InputBase/index.tsx

Issue: #1161
Changes were made to the InputBase component to ensure correct spacing when isClearable = true in the Search component. The issue of content overlapping the clear button was fixed.

fix(search): Fix the overlapping content issue around the clear button

---

.changeset/a11y-useFocusLock-hook-disabled-elements.md
packages/react-magma-dom/src/components/Modal/Modal.stories.tsx
packages/react-magma-dom/src/hooks/useFocusLock.test.js
packages/react-magma-dom/src/hooks/useFocusLock.ts

Issue: #1272
Fix the `useFocusLock` hook if the first or last element is disabled.

fix(useFocusLock): Fix the `useFocusLock` hook if the first or last element is disabled.

---

.changeset/fix-stories-files.md
packages/react-magma-dom/tsconfig.json

Issue: #1477
Remove `.stories.` files from the production bundle.

fix(.srories.): Remove `.stories.` files from the production bundle.

---

.changeset/a11y-timePicker-shortcut.md
website/react-magma-docs/src/pages/api/time-picker.mdx

Issue: #1400 
improve TimePicker Internationalization example 
check explanation and aria-labels for the example in docs under `api/time-picker/#internationalization`

A11y Documentation: Time Picker - Internationalization

---

.changeset/a11y-checkBox-labels-not-read.md
packages/react-magma-dom/src/components/Checkbox/index.tsx

Issue: #1122
Fix for unreadable labels in `CheckBox` for screen readers.

fix(CheckBox): Fix for unreadable labels in `CheckBox` for screen readers.

---

.changeset/fix-select-placeholder-color.md
packages/react-magma-dom/src/components/Select/MultiSelect.tsx
packages/react-magma-dom/src/components/Select/Select.tsx
packages/react-magma-dom/src/components/Select/shared.ts

Issue: #770
Fix the placeholder's color.

fix(Select): Fix the placeholder's color

---

.changeset/implement-scrollspy-in-docs.md
website/react-magma-docs/src/components/SubPageTabs/index.js

Issue: #1023
Implement scrollspy in docs.
Open docs -> Open any component -> Scroll to a new tab -> Check if the `On this page` navigation behaves as intended.

feat(react-magma-docs): Implement scrollspy.

---

.changeset/fix-treeview-issues-from-verification.md
packages/react-magma-dom/jest.config.js
packages/react-magma-dom/src/components/Checkbox/index.tsx
packages/react-magma-dom/src/components/TreeView/TreeItem.tsx
packages/react-magma-dom/src/components/TreeView/TreeView.stories.tsx
packages/react-magma-dom/src/components/TreeView/TreeView.test.js
packages/react-magma-dom/src/components/TreeView/useTreeItem.ts
packages/react-magma-dom/src/components/TreeView/useTreeView.ts
packages/react-magma-dom/src/components/TreeView/utils.ts
packages/react-magma-dom/src/utils/index.ts
packages/react-magma-dom/src/utils/utils.test.jsx
website/react-magma-docs/src/pages/api/tree-view.mdx

Issue: #1490
Fixed list of issues from this ticket https://github.com/cengage/react-magma/issues/1490
This ticket https://github.com/cengage/react-magma/issues/1490 includes testing steps

fix(treeview): fix TreeView issues from verification

---

.changeset/a11y-button-remove-animation-presses.md
packages/react-magma-dom/src/components/Alert/__snapshots__/Alert.test.js.snap
packages/react-magma-dom/src/components/Button/__snapshots__/Button.test.js.snap
packages/react-magma-dom/src/components/ButtonGroup/__snapshots__/ButtonGroup.test.js.snap
packages/react-magma-dom/src/components/IconButton/__snapshots__/IconButton.test.js.snap
packages/react-magma-dom/src/components/SkipLink/__snapshots__/SkipLink.test.js.snap
packages/react-magma-dom/src/components/StyledButton/index.tsx
packages/react-magma-dom/src/components/StyledButton/styles.ts

Issue: #1295
Remove animation on `Button` presses.
Open docs/storybook -> Open `Button` component -> Click on button -> Check styles and animations.

fix(Button): Remove animation on `Button` presses.

---

.changeset/feat-input-help-text.md
packages/react-magma-dom/src/components/Input/Input.stories.tsx
packages/react-magma-dom/src/components/Input/index.tsx
packages/react-magma-dom/src/components/InputBase/index.tsx
website/react-magma-docs/src/pages/api/input.mdx
website/react-magma-docs/src/pages/api/select.mdx

Issue: #1163 
Update Input additional children position based on lable position
check Input with help link behavior based on label position and visibility

Update Input additional children position based on lable position

---

.changeset/feat-input-error-state-update-colors.md
packages/dropzone/src/components/dropzone/Dropzone.tsx
packages/dropzone/src/components/dropzone/Preview.tsx
packages/react-magma-dom/src/components/Checkbox/Checkbox.test.js
packages/react-magma-dom/src/components/Input/Input.test.js
packages/react-magma-dom/src/components/Input/InputMessage.tsx
packages/react-magma-dom/src/components/InputBase/index.tsx
packages/react-magma-dom/src/components/NativeSelect/NativeSelect.test.js
packages/react-magma-dom/src/components/NativeSelect/NativeSelect.tsx
packages/react-magma-dom/src/components/Radio/Radio.test.js
packages/react-magma-dom/src/components/Radio/index.tsx
packages/react-magma-dom/src/components/SelectionControls/InputStyles.tsx

Issue: #1423
Update colors for error message, icon and border in dark mode.
Open `Input` -> Set dark mode (`isInverse` prop) -> Add error message  -> Check message, icon, and border colors.

feat(Input): Update colors for error message, icon and border in dark mode.

---

.changeset/fix-timePicker-adjust-AM-PM-width.md
packages/react-magma-dom/src/components/TimePicker/TimePicker.tsx

Issue: #1488
Fixed AM/PM width in the `TimePicker`.
Open `TimePicker` in the docs -> Scroll to the `Internationalization` section -> Check styles.

fix(TimePicker): Fixed AM/PM width in the `TimePicker`.

---

.changeset/treeview-undefined.md
packages/react-magma-dom/src/components/TreeView/TreeItem.test.js
packages/react-magma-dom/src/components/TreeView/TreeItem.tsx
packages/react-magma-dom/src/components/TreeView/TreeView.stories.tsx
packages/react-magma-dom/src/components/TreeView/TreeView.tsx
packages/react-magma-dom/src/components/TreeView/TreeViewContext.ts
packages/react-magma-dom/src/components/TreeView/useTreeItem.ts
packages/react-magma-dom/src/components/TreeView/useTreeView.ts
packages/react-magma-dom/src/components/TreeView/utils.ts

Issue: #1518
- added optional chaining to prevent undefined error
- the issue with max call size stack was because itemIds were not unique, so just an issue with my example
- reformatted a few files, so review this PR while hiding whitespace changed
N/A

fix(TreeView): Fix undefined error

---

.changeset/feat-heading-add-props.md
packages/react-magma-dom/src/components/Heading/Heading.stories.tsx
packages/react-magma-dom/src/components/Heading/Heading.test.js
website/react-magma-docs/src/pages/api/heading.mdx

Issue: #1507
Add a description of the `noTopMargin` and `noBottomMargin` props to the documentation.
Open documentation -> Open `Heading` -> Check new existing description for `noTopMargin` and `noBottomMargin` props.

feat(Heading): Add a description of the `noTopMargin` and `noBottomMargin` props to the documentation.

---

.changeset/a11y-datepicker-calendar-header-columns.md
packages/react-magma-dom/src/components/DatePicker/CalendarMonth.tsx
website/react-magma-docs/src/pages/api/date-pickers.mdx

Issue: #1341
Add `aria-label` to calendar header columns.
Open `DatePicker` -> Open DevTools -> Check that each header column has the correct `aria-label`.

fix(DatePicker): Add `aria-label` to calendar header columns.

---

.changeset/docs-contguidelines.md
website/react-magma-docs/src/components/SubPageTabs/index.js

Issue: none
Contribution guidelines page was not loading because it doesn't have any headings
Before:
Confirm that the Contribution Guidelines page can be reached

docs: Fix contribution guidelines page

---

.changeset/fix-input-help-link.md
packages/react-magma-dom/src/components/FormFieldContainer/FormFieldContainer.tsx
packages/react-magma-dom/src/components/Input/Input.stories.tsx
packages/react-magma-dom/src/components/Input/index.tsx
packages/react-magma-dom/src/components/InputBase/index.tsx
website/react-magma-docs/src/pages/api/input.mdx

Issue: #1163 
Fix HelpLink position on inputs.
Fix errors in code example in the docs
Test the styling and design under  /story/input--help-link
Review the Doc example under /api/input/#help_link

fix/Input: Fix HelpLink position on inputs.

---

.changeset/treeview-undefined-2.md
packages/react-magma-dom/src/components/TreeView/useTreeView.ts
packages/react-magma-dom/src/components/TreeView/utils.ts

Issue: none
MAST is reporting running into `Error: Uncaught [TypeError: Cannot read properties of undefined (reading 'isDisabled')].` in our pre-release version. Adding null checking to a few more places to see if that fixes is.
Can't reproduce this issue locally, so will merge and send to MAST team to test.

fix(TreeView): Fix undefined problem

---

.changeset/input-props.md
packages/react-magma-dom/src/components/InputBase/index.tsx

Issue: none
Clarify to adopters what each of the style props for Input mean

fix(Input): Improve descriptions for `inputWrapperStyle` and `containerStyle` props.

---

.changeset/tree-unitTests.md
packages/react-magma-dom/src/components/TreeView/TreeView.stories.tsx
packages/react-magma-dom/src/components/TreeView/TreeView.test.js
packages/react-magma-dom/src/components/TreeView/useTreeView.ts
website/react-magma-docs/src/pages/api/tree-view.mdx

Issue: none
Adding unit tests for recursively created items, and removing console.log for items
N/A

fix(TreeView): Add more unit tests

---

packages/react-magma-dom/src/components/Select/shared.ts

Issue: #1217 
added not-allowed pointer styling for disabled items

Select: Support disabling individual items - adding not-allowed pointer

---

.changeset/fix-toast-time-duration.md
packages/react-magma-dom/src/components/AlertBase/index.tsx
packages/react-magma-dom/src/components/Input/Input.stories.tsx

Issue: #1560
Fix ring time duration.
Go to example in storybook -> Change Toast Duration -> Open Toast

fix(Toast): ring time duration

---

.changeset/feat-charts-documentation-v2.md
website/react-magma-docs/src/pages/data-visualization/introduction.mdx

Issue: #
Change the name from 'Get Started' to 'Getting Started'.

fix(Charts): change name of the sub-page and title

---

.changeset/chore-gh-templates.md
.github/CODEOWNERS
.github/pull_request_template.md

Issue: none
- Updating CODEOWNERS file so all the devs get automatically added as reviewers on PRs.
- Updating our PR checklist and replacing `Issue:` with `Closes` so that the ticket can get auto linked.
N/A
When a new PR is opened, confirmed that devs are added as reviewers and that adding a ticket number after "closes" auto links the ticket to the PR.

chore: Fix codeowners and update PR template

---

.changeset/fix-Typography-images-wrong-size.md
website/react-magma-docs/src/pages/data-visualization/chart-types.css

Issue: #1635
Fix wrong size on images in the documentation.

fix(Typography): Wrong size on images in the documentation.

---

.changeset/fix-multiselect-page-refreshs.md
packages/react-magma-dom/src/components/Select/SelectContainer.tsx

Closes: #1656
Fixed a bug where the page would refresh when the selected element was clicked, changing form to div.
Open MultiSelect -> Select 2 or more items -> Remove the first one -> Notice that the page does not refresh.

fix(MultiSelect): Fix a bug where the page refreshes when you click on a selected item.

---

.changeset/chore-bump-dom.md

chore: bump dom to 4.8.0-next.15

chore: bump dom patch versions

---

.changeset/fix-tableOverflowv2.md
packages/react-magma-dom/src/components/Table/Table.tsx

Closes: #1673
added `TableWrapper` and replaced `@media` query with `@container` query to handle overflow 
navigate to Table examples in doc and storybook and observe behavior
https://storybook-preview-1674--upbeat-sinoussi-f675aa.netlify.app/?path=/story/table--with-dropdown
https://docs-preview-1674--upbeat-sinoussi-f675aa.netlify.app/api/table/#min-width

fix(Table): fix min-width overflow issues

---

.changeset/fix-Docs-pre-release-issues.md
website/react-magma-docs/src/components/DemoModal/index.js
website/react-magma-docs/src/pages/api-intro/styles-and-themes.mdx
website/react-magma-docs/src/pages/api/button.mdx
website/react-magma-docs/src/pages/api/modal.mdx
website/react-magma-docs/src/pages/api/select.mdx
website/react-magma-docs/src/pages/api/stepper.mdx
website/react-magma-docs/src/pages/api/toast.mdx
website/react-magma-docs/src/pages/api/toggle-button.mdx

Closes: #1672
Fix pre release issues.
Open documentation -> Check issues

fix(Docs): Fix pre release issues.

---

.changeset/fix-AppBar.md
.changeset/revert-fix-AppBar.md
packages/react-magma-dom/src/components/AppBar/AppBar.stories.tsx
packages/react-magma-dom/src/components/SkipLink/index.tsx

This reverts commit c7d25723e18ffd328dc6786dc965bf0f1dbba104.
reverts pr #1676

Revert "fix(SkipLink): Fix overlap with the SkipLink component when used with"

---

.changeset/react-version-docs.md
README.md
website/react-magma-docs/src/pages/api-intro/introduction.mdx
website/react-magma-docs/src/pages/data-visualization/introduction.mdx

Closes: none
Update our docs to accurately state what version of React we support
Check out docs site & README

chore: Update supported React version in docs

---

.changeset/feat-treeview-is-top-level-selectable.md
packages/react-magma-dom/src/components/TreeView/TreeItem.tsx
packages/react-magma-dom/src/components/TreeView/TreeView.stories.tsx
packages/react-magma-dom/src/components/TreeView/TreeView.test.js
packages/react-magma-dom/src/components/TreeView/TreeViewContext.ts
packages/react-magma-dom/src/components/TreeView/useTreeItem.ts
packages/react-magma-dom/src/components/TreeView/useTreeView.ts
packages/react-magma-dom/src/components/TreeView/utils.ts
website/react-magma-docs/src/pages/api/tree-view.mdx

Closes: #1631 
* Added a new isTopLevelSelectable prop to TreeView component props.
* Modified TreeViewContext to include isTopLevelSelectable.
* Updated TreeItem component to conditionally render checkboxes based on isTopLevelSelectable.
* Adjusted useTreeItem and useTreeView hooks to handle isTopLevelSelectable.
* Added unit tests for the new functionality.
* Updated documentation and storybook examples to demonstrate usage of isTopLevelSelectable.
* Verify Checkbox Behavior:
* Set selectable to TreeViewSelectable.multi and isTopLevelSelectable to false.
* Ensure top-level items do not display checkboxes.
* Checkbox Display Scenarios:
* Test with two top-level items where both are parents; confirm neither displays checkboxes.
* Test with mixed parent and leaf items at the top level; …

feat/TreeView add isTopLevelSelectable prop

---

.changeset/support-icons3-1.md
package-lock.json
packages/charts/package.json
packages/dropzone/package.json
packages/react-magma-dom/package.json
packages/schema-renderer/package.json
patterns/header/package.json
website/react-magma-docs/package.json

Closes: #1191 #1204
Update react-magma-icons version to one that:
1. Updated uuid version
2. Adds X icon 🤮 
3. Adds Draft Orders icon
- [-] Tests that prove the fix is effective or that the feature works have been added
- Confirm that new icons are visible on docs site, and are usable on code sandbox
- Confirm that installing the latest dom version doesn't give an error about a conflicting icons version

chore: Update to react-magma-icons v3.1.0

---

.changeset/fix-SkipLink-prop.md
packages/react-magma-dom/src/components/AppBar/AppBar.stories.tsx
packages/react-magma-dom/src/components/Hyperlink/index.tsx
packages/react-magma-dom/src/components/SkipLink/SkipLink.stories.tsx
packages/react-magma-dom/src/components/SkipLink/index.tsx
website/react-magma-docs/src/pages/api/appbar.mdx
website/react-magma-docs/src/pages/api/skip-link.mdx

Closes: #1686
Made the `to` prop optional

SkipLink: Should not accept "to" prop

---

.changeset/feat-DefinitionList-DefinitionList.md
.changeset/fix-List-wrong-markup.md
packages/react-magma-dom/src/components/DefinitionList/DefinitionList.stories.tsx
packages/react-magma-dom/src/components/DefinitionList/DefinitionList.test.js
packages/react-magma-dom/src/components/DefinitionList/DefinitionList.tsx
packages/react-magma-dom/src/components/DefinitionList/DefinitionListItem.tsx
packages/react-magma-dom/src/components/DefinitionList/index.ts
packages/react-magma-dom/src/components/List/ListItem.tsx
packages/react-magma-dom/src/index.ts
website/react-magma-docs/src/pages/api/list.mdx

Closes:  #1243
Added new types of List:
- DefinitionList and DefinitionListItem components
Updated storybook and React Magma docs.
Storybook:
React Magma Docs:
Storybook:
- Go to DefinitionList 
React Magma Docs:
- Open React Magma Docs
- Go to Components -> List 
- Check `Description` prop is updated
- Check `DefinitionList` section

feat(DefinitionList): New DefinitionList and DefinitionListItem components

---

.changeset/landing-links.md
.changeset/sync-landing.md
website/react-magma-landing/package.json

Closes: #1716 
Updating dev branch to new landing package version and removing changeset
- [-] Corresponding changes to the documentation have been made
- [-] New and existing unit tests pass locally with the proposed changes
- [-] Tests that prove the fix is effective or that the feature works have been added
Nothing to test

chore: Resync after landing updates

---

.changeset/uuid copy.md
.lintstagedrc
website/react-magma-docs/src/pages/api/input.mdx
website/react-magma-docs/src/pages/api/list.mdx
website/react-magma-docs/src/pages/api/popover.mdx
website/react-magma-docs/src/pages/api/skip-link.mdx

Closes: #1534
- Ensured ESLint and Prettier run on staged MDX files before commit
- ran the command `npm run fix:all` to style up the missed files
1. Stage an MDX file in the website directory with a linting error
2. Attempt to commit - the pre-commit hook should catch the linting error (
3. Fix the error and retry the commit to confirm it succeeds

chore(eslint): .lintstagedrc to lint mdx files in precommit hook

---

.changeset/feat-popover-fix-comments.md
packages/react-magma-dom/src/components/InputBase/index.tsx
packages/react-magma-dom/src/components/Popover/Popover.stories.tsx
packages/react-magma-dom/src/components/Popover/Popover.tsx
packages/react-magma-dom/src/components/Popover/PopoverContent.tsx
packages/react-magma-dom/src/components/Popover/__snapshots__/Popover.test.js.snap
packages/react-magma-dom/src/components/StyledButton/index.tsx
website/react-magma-docs/src/pages/api/popover.mdx

Closes: #927
Fix comments: add functionality to use `Esc` button everywhere, fix docs, add `maxWidth` to content.
Open Popover -> Check that everything works as expected.

feat(Popover): Add functionality to use `Esc` button, fix docs, add `maxWidth` to content

---

.changeset/curly-singers-dress.md
.changeset/dropzone-types.md
.changeset/feat-DefinitionList-DefinitionList.md
.changeset/feat-TreeView-add-expandAll-and-collapseAll.md
.changeset/feat-popover-fix-comments.md
.changeset/feat-treeview-is-top-level-selectable.md
.changeset/fix-DefinitionList-docs-errors.md
.changeset/fix-Dropdown-add-icon-parent-level.md
.changeset/fix-Dropdown-not-displayed-above-elements.md
.changeset/fix-Input-not-properly-update-value.md
.changeset/fix-SkipLink-prop.md
.changeset/fix-Tabs-Improve-functionality-small-screen.md
.changeset/fix-TreeView-keyboard.md
.changeset/fix-Typography-types.md
.changeset/fix-heading-navtabs-props-error.md
.changeset/fix-tooltip-replace-popper-with-floating-ui.md
.changeset/inputFirefox.md
.changeset/nine-roses-beam.md
.changeset/pre.json
.changeset/selfish-bees-walk.md
.changeset/simple-pag.md
.changeset/simple-pagination.md
.changeset/tender-lizards-kneel.md
.changeset/uuid.md
package-lock.json
packages/charts/package.json
packages/react-magma-dom/CHANGELOG.md
packages/schema-renderer/package.json
website/react-magma-docs/package.json

Closes: -
Cleaning up changesets ahead of release PR and also trying to fix pipeline build.
N/A

chore: Clean up changesets

---

.changeset/fix-pre-release-docs-issues.md
packages/react-magma-dom/src/components/Pagination/Pagination.tsx
website/react-magma-docs/src/pages/api/pagination.mdx
website/react-magma-docs/src/pages/api/popover.mdx
website/react-magma-docs/src/pages/api/search.mdx
website/react-magma-docs/src/pages/api/tree-view.mdx

Closes: #1757
Fix pre-release issues
Check fixed issues

fix(docs): fix pre-release issues

---

.changeset/fix-Popover-update-z-index.md
packages/react-magma-dom/src/components/Popover/PopoverContent.tsx

Update z-index for Popover
Open Popover -> Check z-index

fix(popover): update z-index to 996

---

.changeset/fix-Input-not-properly-update-value.md
.changeset/revert-Input-not-properly-update-value.md
packages/react-magma-dom/src/components/Input/Input.stories.tsx
packages/react-magma-dom/src/components/Input/Input.test.js
packages/react-magma-dom/src/components/InputBase/index.tsx

Closes: #
reverted changes in pr 1741

fix(input): revert fix(input) Does not update value as expected #1741

---

.changeset/updateReadMe.md
.github/CODEOWNERS
README.md

Closes: none
It was brought to my attention that our README's system dependencies were out of date. Also updating our codeowners so it actually automatically adds reviewers (was missing an asterisk to account for any nested changes)
N/A
- Opening a PR automatically adds the entire dev team as reviewers

chore: Update README and CODEOWNERS

---

.changeset/chore-deploy-v2.md
.github/workflows/deploy-v2-docs.yml
website/react-magma-landing/templates/_redirects

Closes: #1788
* added deploy-v2-docs.yml to deploy v2 docs
* redirected v2 to https://2-6-0--upbeat-sinoussi-f675aa.netlify.app/:splat

chore(deps): add deploy-v2-docs.yml to deploy v2 docs

---

.changeset/chore-deploy-v2.md
.github/workflows/deploy-v2-docs.yml
website/react-magma-landing/templates/_redirects

Closes: #1788
add change to main

chore(deps): add deploy-v2-docs.yml to deploy v2 docs (#1789)

---

.changeset/chore-deploy-v2.md

fix(landing): edit the changeset to release landing

---

.changeset/chore-docs-add-useDeviceDetect-page.md
packages/react-magma-dom/src/hooks/useDeviceDetect.ts
packages/react-magma-dom/src/index.ts
website/react-magma-docs/src/pages/api/use-device-detect.mdx

Add page for `useDeviceDetect hook`
Open documentation -> useDeviceDetect hook

chore(docs): add page for useDeviceDetect hook

---

.changeset/fix-Dropdown-Performance-issue.md
packages/react-magma-dom/src/components/ButtonGroup/__snapshots__/ButtonGroup.test.js.snap
packages/react-magma-dom/src/components/Combobox/Combobox.tsx
packages/react-magma-dom/src/components/Combobox/MultiCombobox.tsx
packages/react-magma-dom/src/components/Combobox/index.tsx
packages/react-magma-dom/src/components/DatePicker/index.tsx
packages/react-magma-dom/src/components/Dropdown/Dropdown.tsx
packages/react-magma-dom/src/components/Dropdown/DropdownContent.tsx
packages/react-magma-dom/src/components/Popover/Popover.tsx
packages/react-magma-dom/src/components/Popover/PopoverContent.tsx
packages/react-magma-dom/src/components/Select/ItemsList.tsx
packages/react-magma-dom/src/components/Select/MultiSelect.tsx
packages/react-magma-dom/src/components/Select/Select.tsx
packages/react-magma-dom/src/components/Select/index.tsx
packages/react-magma-dom/src/components/Tooltip/index.tsx
packages/react-magma-dom/src/hooks/useMagmaFloating.ts

Closes: #1813
- Added cleaning for the floating state to improve performance
Documentation reference: [link](https://floating-ui.com/docs/autoupdate#:~:text=and%20floating%20element.-,Alternatively,-%2C%20if%20you%E2%80%99ve%20hidden)

fix(Dropdown & Select & Combobox & DatePicker & Popover & Tooltip): Fix performance functionality.

---

.changeset/icons-v.md
package-lock.json
packages/charts/package.json
packages/dropzone/package.json
packages/react-magma-dom/package.json
packages/schema-renderer/package.json
patterns/header/package.json
website/react-magma-docs/package.json

Closes: #1777
Update react-magma-icons version to support new Icons: Phishing, Question Mark, Target, Media, Notebook
- [-] New and existing unit tests pass locally with the proposed changes
- [-] Tests that prove the fix is effective or that the feature works have been added
Confirm that icons are visible in docs site

feat(icons): Update react-magma-icons version to 3.2.0

---

.changeset/chore-fix-dom-version.md
package-lock.json
packages/charts/package.json
packages/dropzone/package.json
packages/react-magma-dom/package.json
packages/schema-renderer/package.json
patterns/header/package.json
website/react-magma-docs/package.json

Closes: #
fix react-magma-dom next version

chore(docs): fix react-magma-dom next version

---

.changeset/fix-button-round-styles.md
packages/react-magma-dom/src/components/Button/__snapshots__/Button.test.js.snap
packages/react-magma-dom/src/components/Hyperlink/Hyperlink.test.js
packages/react-magma-dom/src/components/StyledButton/StyledButton.test.js
packages/react-magma-dom/src/components/StyledButton/styles.ts

Closes: #1869 
Fix styles for `Button` with `shape="round"` 
Open Storybook -> Button -> `shape="round"`

fix(button): fix styles for `round` button

---

.changeset/feat-TimePicker-add-auto-fill.md
.vscode/settings.json
packages/react-magma-dom/src/components/TimePicker/TimePicker.test.js
packages/react-magma-dom/src/components/TimePicker/useTimePicker.ts

Closes: #1892 
Add auto fill to TimePicker
Open Storybook -> TimePicker -> check functionality:
1. Set the hour -> minutes are automatically set to “00”;
2. Set the minutes -> hours are automatically set to “12”.

feat(TimePicker): add auto fill

---

.changeset/fix-Popover-blur-behavior.md
packages/react-magma-dom/src/components/Popover/Popover.stories.tsx
packages/react-magma-dom/src/components/Popover/Popover.tsx

Closes: #1911
Fix a bug with several popovers (focus behavior)
Open Storybook -> Several Popovers -> Check behavior

fix(Popover): Fix a bug with several popovers

---

.changeset/fix-DatePicker-fix-color-issue.md
packages/react-magma-dom/src/components/DatePicker/CalendarDay.tsx

Closes: #
Fix a small color issue for a11y
Open DatePicker -> Type the date which is out of range -> Check styles (normal and inversed)

fix(DatePicker): Fix a small color issue for a11y
